language: minimal

services:
  - docker

script:
  - make deb-package

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file_glob: true
  file: packages/*.deb
  skip_cleanup: true
  draft: true
  on:
    tags: true

notifications:
  email:
    - sergey@divpro.ru
