// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.18.3
// source: types/v2/network.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NetworkSchemeType int32

const (
	NetworkSchemeType_UNDEFINED_SCHEME NetworkSchemeType = 0
	NetworkSchemeType_ROUTED           NetworkSchemeType = 1
	NetworkSchemeType_BRIDGE           NetworkSchemeType = 2
	NetworkSchemeType_VXLAN            NetworkSchemeType = 3
	NetworkSchemeType_VLAN             NetworkSchemeType = 4
)

// Enum value maps for NetworkSchemeType.
var (
	NetworkSchemeType_name = map[int32]string{
		0: "UNDEFINED_SCHEME",
		1: "ROUTED",
		2: "BRIDGE",
		3: "VXLAN",
		4: "VLAN",
	}
	NetworkSchemeType_value = map[string]int32{
		"UNDEFINED_SCHEME": 0,
		"ROUTED":           1,
		"BRIDGE":           2,
		"VXLAN":            3,
		"VLAN":             4,
	}
)

func (x NetworkSchemeType) Enum() *NetworkSchemeType {
	p := new(NetworkSchemeType)
	*p = x
	return p
}

func (x NetworkSchemeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NetworkSchemeType) Descriptor() protoreflect.EnumDescriptor {
	return file_types_v2_network_proto_enumTypes[0].Descriptor()
}

func (NetworkSchemeType) Type() protoreflect.EnumType {
	return &file_types_v2_network_proto_enumTypes[0]
}

func (x NetworkSchemeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NetworkSchemeType.Descriptor instead.
func (NetworkSchemeType) EnumDescriptor() ([]byte, []int) {
	return file_types_v2_network_proto_rawDescGZIP(), []int{0}
}

type NetworkEndPoint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LinkName  string `protobuf:"bytes,1,opt,name=link_name,json=linkName,proto3" json:"link_name,omitempty"`
	LinkIndex uint32 `protobuf:"varint,2,opt,name=link_index,json=linkIndex,proto3" json:"link_index,omitempty"`
	// Types that are assignable to Attrs:
	//
	//	*NetworkEndPoint_VlanAttrs
	//	*NetworkEndPoint_VxlanAttrs
	//	*NetworkEndPoint_IPFabricAttrs
	Attrs isNetworkEndPoint_Attrs `protobuf_oneof:"attrs"`
}

func (x *NetworkEndPoint) Reset() {
	*x = NetworkEndPoint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_v2_network_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NetworkEndPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkEndPoint) ProtoMessage() {}

func (x *NetworkEndPoint) ProtoReflect() protoreflect.Message {
	mi := &file_types_v2_network_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkEndPoint.ProtoReflect.Descriptor instead.
func (*NetworkEndPoint) Descriptor() ([]byte, []int) {
	return file_types_v2_network_proto_rawDescGZIP(), []int{0}
}

func (x *NetworkEndPoint) GetLinkName() string {
	if x != nil {
		return x.LinkName
	}
	return ""
}

func (x *NetworkEndPoint) GetLinkIndex() uint32 {
	if x != nil {
		return x.LinkIndex
	}
	return 0
}

func (m *NetworkEndPoint) GetAttrs() isNetworkEndPoint_Attrs {
	if m != nil {
		return m.Attrs
	}
	return nil
}

func (x *NetworkEndPoint) GetVlanAttrs() *NetworkEndPoint_Vlan {
	if x, ok := x.GetAttrs().(*NetworkEndPoint_VlanAttrs); ok {
		return x.VlanAttrs
	}
	return nil
}

func (x *NetworkEndPoint) GetVxlanAttrs() *NetworkEndPoint_Vxlan {
	if x, ok := x.GetAttrs().(*NetworkEndPoint_VxlanAttrs); ok {
		return x.VxlanAttrs
	}
	return nil
}

func (x *NetworkEndPoint) GetIPFabricAttrs() *NetworkEndPoint_IPFabric {
	if x, ok := x.GetAttrs().(*NetworkEndPoint_IPFabricAttrs); ok {
		return x.IPFabricAttrs
	}
	return nil
}

type isNetworkEndPoint_Attrs interface {
	isNetworkEndPoint_Attrs()
}

type NetworkEndPoint_VlanAttrs struct {
	VlanAttrs *NetworkEndPoint_Vlan `protobuf:"bytes,3,opt,name=vlan_attrs,json=vlanAttrs,proto3,oneof"`
}

type NetworkEndPoint_VxlanAttrs struct {
	VxlanAttrs *NetworkEndPoint_Vxlan `protobuf:"bytes,4,opt,name=vxlan_attrs,json=vxlanAttrs,proto3,oneof"`
}

type NetworkEndPoint_IPFabricAttrs struct {
	IPFabricAttrs *NetworkEndPoint_IPFabric `protobuf:"bytes,5,opt,name=ipfabric_attrs,json=ipfabricAttrs,proto3,oneof"`
}

func (*NetworkEndPoint_VlanAttrs) isNetworkEndPoint_Attrs() {}

func (*NetworkEndPoint_VxlanAttrs) isNetworkEndPoint_Attrs() {}

func (*NetworkEndPoint_IPFabricAttrs) isNetworkEndPoint_Attrs() {}

type NetworkSchemeOpts struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ifname string `protobuf:"bytes,1,opt,name=ifname,proto3" json:"ifname,omitempty"`
	MTU    uint32 `protobuf:"varint,2,opt,name=mtu,proto3" json:"mtu,omitempty"`
	// Types that are assignable to Attrs:
	//
	//	*NetworkSchemeOpts_Vlan
	//	*NetworkSchemeOpts_Vxlan
	//	*NetworkSchemeOpts_Router
	//	*NetworkSchemeOpts_Bridge
	Attrs    isNetworkSchemeOpts_Attrs `protobuf_oneof:"attrs"`
	Addrs    []string                  `protobuf:"bytes,21,rep,name=addrs,proto3" json:"addrs,omitempty"`
	Gateway4 string                    `protobuf:"bytes,22,opt,name=gateway4,proto3" json:"gateway4,omitempty"`
	Gateway6 string                    `protobuf:"bytes,23,opt,name=gateway6,proto3" json:"gateway6,omitempty"`
}

func (x *NetworkSchemeOpts) Reset() {
	*x = NetworkSchemeOpts{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_v2_network_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NetworkSchemeOpts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkSchemeOpts) ProtoMessage() {}

func (x *NetworkSchemeOpts) ProtoReflect() protoreflect.Message {
	mi := &file_types_v2_network_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkSchemeOpts.ProtoReflect.Descriptor instead.
func (*NetworkSchemeOpts) Descriptor() ([]byte, []int) {
	return file_types_v2_network_proto_rawDescGZIP(), []int{1}
}

func (x *NetworkSchemeOpts) GetIfname() string {
	if x != nil {
		return x.Ifname
	}
	return ""
}

func (x *NetworkSchemeOpts) GetMTU() uint32 {
	if x != nil {
		return x.MTU
	}
	return 0
}

func (m *NetworkSchemeOpts) GetAttrs() isNetworkSchemeOpts_Attrs {
	if m != nil {
		return m.Attrs
	}
	return nil
}

func (x *NetworkSchemeOpts) GetVlan() *NetworkSchemeOpts_Attrs_VLAN {
	if x, ok := x.GetAttrs().(*NetworkSchemeOpts_Vlan); ok {
		return x.Vlan
	}
	return nil
}

func (x *NetworkSchemeOpts) GetVxlan() *NetworkSchemeOpts_Attrs_VxLAN {
	if x, ok := x.GetAttrs().(*NetworkSchemeOpts_Vxlan); ok {
		return x.Vxlan
	}
	return nil
}

func (x *NetworkSchemeOpts) GetRouter() *NetworkSchemeOpts_Attrs_Router {
	if x, ok := x.GetAttrs().(*NetworkSchemeOpts_Router); ok {
		return x.Router
	}
	return nil
}

func (x *NetworkSchemeOpts) GetBridge() *NetworkSchemeOpts_Attrs_Bridge {
	if x, ok := x.GetAttrs().(*NetworkSchemeOpts_Bridge); ok {
		return x.Bridge
	}
	return nil
}

func (x *NetworkSchemeOpts) GetAddrs() []string {
	if x != nil {
		return x.Addrs
	}
	return nil
}

func (x *NetworkSchemeOpts) GetGateway4() string {
	if x != nil {
		return x.Gateway4
	}
	return ""
}

func (x *NetworkSchemeOpts) GetGateway6() string {
	if x != nil {
		return x.Gateway6
	}
	return ""
}

type isNetworkSchemeOpts_Attrs interface {
	isNetworkSchemeOpts_Attrs()
}

type NetworkSchemeOpts_Vlan struct {
	Vlan *NetworkSchemeOpts_Attrs_VLAN `protobuf:"bytes,11,opt,name=vlan,proto3,oneof"`
}

type NetworkSchemeOpts_Vxlan struct {
	Vxlan *NetworkSchemeOpts_Attrs_VxLAN `protobuf:"bytes,12,opt,name=vxlan,proto3,oneof"`
}

type NetworkSchemeOpts_Router struct {
	Router *NetworkSchemeOpts_Attrs_Router `protobuf:"bytes,13,opt,name=router,proto3,oneof"`
}

type NetworkSchemeOpts_Bridge struct {
	Bridge *NetworkSchemeOpts_Attrs_Bridge `protobuf:"bytes,14,opt,name=bridge,proto3,oneof"`
}

func (*NetworkSchemeOpts_Vlan) isNetworkSchemeOpts_Attrs() {}

func (*NetworkSchemeOpts_Vxlan) isNetworkSchemeOpts_Attrs() {}

func (*NetworkSchemeOpts_Router) isNetworkSchemeOpts_Attrs() {}

func (*NetworkSchemeOpts_Bridge) isNetworkSchemeOpts_Attrs() {}

type NetworkEndPoint_Port struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LinkName  string `protobuf:"bytes,1,opt,name=link_name,json=linkName,proto3" json:"link_name,omitempty"`
	LinkIndex uint32 `protobuf:"varint,2,opt,name=link_index,json=linkIndex,proto3" json:"link_index,omitempty"`
}

func (x *NetworkEndPoint_Port) Reset() {
	*x = NetworkEndPoint_Port{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_v2_network_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NetworkEndPoint_Port) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkEndPoint_Port) ProtoMessage() {}

func (x *NetworkEndPoint_Port) ProtoReflect() protoreflect.Message {
	mi := &file_types_v2_network_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkEndPoint_Port.ProtoReflect.Descriptor instead.
func (*NetworkEndPoint_Port) Descriptor() ([]byte, []int) {
	return file_types_v2_network_proto_rawDescGZIP(), []int{0, 0}
}

func (x *NetworkEndPoint_Port) GetLinkName() string {
	if x != nil {
		return x.LinkName
	}
	return ""
}

func (x *NetworkEndPoint_Port) GetLinkIndex() uint32 {
	if x != nil {
		return x.LinkIndex
	}
	return 0
}

type NetworkEndPoint_Vlan struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VlanID uint32                  `protobuf:"varint,1,opt,name=vlan_id,json=vlanId,proto3" json:"vlan_id,omitempty"`
	Ports  []*NetworkEndPoint_Port `protobuf:"bytes,3,rep,name=ports,proto3" json:"ports,omitempty"`
}

func (x *NetworkEndPoint_Vlan) Reset() {
	*x = NetworkEndPoint_Vlan{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_v2_network_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NetworkEndPoint_Vlan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkEndPoint_Vlan) ProtoMessage() {}

func (x *NetworkEndPoint_Vlan) ProtoReflect() protoreflect.Message {
	mi := &file_types_v2_network_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkEndPoint_Vlan.ProtoReflect.Descriptor instead.
func (*NetworkEndPoint_Vlan) Descriptor() ([]byte, []int) {
	return file_types_v2_network_proto_rawDescGZIP(), []int{0, 1}
}

func (x *NetworkEndPoint_Vlan) GetVlanID() uint32 {
	if x != nil {
		return x.VlanID
	}
	return 0
}

func (x *NetworkEndPoint_Vlan) GetPorts() []*NetworkEndPoint_Port {
	if x != nil {
		return x.Ports
	}
	return nil
}

type NetworkEndPoint_Vxlan struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VNI   uint32                  `protobuf:"varint,1,opt,name=vni,proto3" json:"vni,omitempty"`
	Ports []*NetworkEndPoint_Port `protobuf:"bytes,3,rep,name=ports,proto3" json:"ports,omitempty"`
}

func (x *NetworkEndPoint_Vxlan) Reset() {
	*x = NetworkEndPoint_Vxlan{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_v2_network_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NetworkEndPoint_Vxlan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkEndPoint_Vxlan) ProtoMessage() {}

func (x *NetworkEndPoint_Vxlan) ProtoReflect() protoreflect.Message {
	mi := &file_types_v2_network_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkEndPoint_Vxlan.ProtoReflect.Descriptor instead.
func (*NetworkEndPoint_Vxlan) Descriptor() ([]byte, []int) {
	return file_types_v2_network_proto_rawDescGZIP(), []int{0, 2}
}

func (x *NetworkEndPoint_Vxlan) GetVNI() uint32 {
	if x != nil {
		return x.VNI
	}
	return 0
}

func (x *NetworkEndPoint_Vxlan) GetPorts() []*NetworkEndPoint_Port {
	if x != nil {
		return x.Ports
	}
	return nil
}

type NetworkEndPoint_IPFabric struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IPNets []string `protobuf:"bytes,1,rep,name=ipnets,proto3" json:"ipnets,omitempty"`
}

func (x *NetworkEndPoint_IPFabric) Reset() {
	*x = NetworkEndPoint_IPFabric{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_v2_network_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NetworkEndPoint_IPFabric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkEndPoint_IPFabric) ProtoMessage() {}

func (x *NetworkEndPoint_IPFabric) ProtoReflect() protoreflect.Message {
	mi := &file_types_v2_network_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkEndPoint_IPFabric.ProtoReflect.Descriptor instead.
func (*NetworkEndPoint_IPFabric) Descriptor() ([]byte, []int) {
	return file_types_v2_network_proto_rawDescGZIP(), []int{0, 3}
}

func (x *NetworkEndPoint_IPFabric) GetIPNets() []string {
	if x != nil {
		return x.IPNets
	}
	return nil
}

type NetworkSchemeOpts_Attrs_VLAN struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VlanID          uint32 `protobuf:"varint,1,opt,name=vlan_id,json=vlanId,proto3" json:"vlan_id,omitempty"`
	ParentInterface string `protobuf:"bytes,2,opt,name=parent_interface,json=parentInterface,proto3" json:"parent_interface,omitempty"`
}

func (x *NetworkSchemeOpts_Attrs_VLAN) Reset() {
	*x = NetworkSchemeOpts_Attrs_VLAN{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_v2_network_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NetworkSchemeOpts_Attrs_VLAN) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkSchemeOpts_Attrs_VLAN) ProtoMessage() {}

func (x *NetworkSchemeOpts_Attrs_VLAN) ProtoReflect() protoreflect.Message {
	mi := &file_types_v2_network_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkSchemeOpts_Attrs_VLAN.ProtoReflect.Descriptor instead.
func (*NetworkSchemeOpts_Attrs_VLAN) Descriptor() ([]byte, []int) {
	return file_types_v2_network_proto_rawDescGZIP(), []int{1, 0}
}

func (x *NetworkSchemeOpts_Attrs_VLAN) GetVlanID() uint32 {
	if x != nil {
		return x.VlanID
	}
	return 0
}

func (x *NetworkSchemeOpts_Attrs_VLAN) GetParentInterface() string {
	if x != nil {
		return x.ParentInterface
	}
	return ""
}

type NetworkSchemeOpts_Attrs_VxLAN struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VNI           uint32 `protobuf:"varint,1,opt,name=vni,proto3" json:"vni,omitempty"`
	BindInterface string `protobuf:"bytes,2,opt,name=bind_interface,json=bindInterface,proto3" json:"bind_interface,omitempty"`
}

func (x *NetworkSchemeOpts_Attrs_VxLAN) Reset() {
	*x = NetworkSchemeOpts_Attrs_VxLAN{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_v2_network_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NetworkSchemeOpts_Attrs_VxLAN) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkSchemeOpts_Attrs_VxLAN) ProtoMessage() {}

func (x *NetworkSchemeOpts_Attrs_VxLAN) ProtoReflect() protoreflect.Message {
	mi := &file_types_v2_network_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkSchemeOpts_Attrs_VxLAN.ProtoReflect.Descriptor instead.
func (*NetworkSchemeOpts_Attrs_VxLAN) Descriptor() ([]byte, []int) {
	return file_types_v2_network_proto_rawDescGZIP(), []int{1, 1}
}

func (x *NetworkSchemeOpts_Attrs_VxLAN) GetVNI() uint32 {
	if x != nil {
		return x.VNI
	}
	return 0
}

func (x *NetworkSchemeOpts_Attrs_VxLAN) GetBindInterface() string {
	if x != nil {
		return x.BindInterface
	}
	return ""
}

type NetworkSchemeOpts_Attrs_Router struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BindInterface string `protobuf:"bytes,1,opt,name=bind_interface,json=bindInterface,proto3" json:"bind_interface,omitempty"`
	InLimit       uint32 `protobuf:"varint,2,opt,name=in_limit,json=inLimit,proto3" json:"in_limit,omitempty"`
	OutLimit      uint32 `protobuf:"varint,3,opt,name=out_limit,json=outLimit,proto3" json:"out_limit,omitempty"`
	ProcessID     uint32 `protobuf:"varint,100,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
}

func (x *NetworkSchemeOpts_Attrs_Router) Reset() {
	*x = NetworkSchemeOpts_Attrs_Router{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_v2_network_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NetworkSchemeOpts_Attrs_Router) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkSchemeOpts_Attrs_Router) ProtoMessage() {}

func (x *NetworkSchemeOpts_Attrs_Router) ProtoReflect() protoreflect.Message {
	mi := &file_types_v2_network_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkSchemeOpts_Attrs_Router.ProtoReflect.Descriptor instead.
func (*NetworkSchemeOpts_Attrs_Router) Descriptor() ([]byte, []int) {
	return file_types_v2_network_proto_rawDescGZIP(), []int{1, 2}
}

func (x *NetworkSchemeOpts_Attrs_Router) GetBindInterface() string {
	if x != nil {
		return x.BindInterface
	}
	return ""
}

func (x *NetworkSchemeOpts_Attrs_Router) GetInLimit() uint32 {
	if x != nil {
		return x.InLimit
	}
	return 0
}

func (x *NetworkSchemeOpts_Attrs_Router) GetOutLimit() uint32 {
	if x != nil {
		return x.OutLimit
	}
	return 0
}

func (x *NetworkSchemeOpts_Attrs_Router) GetProcessID() uint32 {
	if x != nil {
		return x.ProcessID
	}
	return 0
}

type NetworkSchemeOpts_Attrs_Bridge struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BridgeName string `protobuf:"bytes,1,opt,name=bridge_name,json=bridgeName,proto3" json:"bridge_name,omitempty"`
}

func (x *NetworkSchemeOpts_Attrs_Bridge) Reset() {
	*x = NetworkSchemeOpts_Attrs_Bridge{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_v2_network_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NetworkSchemeOpts_Attrs_Bridge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkSchemeOpts_Attrs_Bridge) ProtoMessage() {}

func (x *NetworkSchemeOpts_Attrs_Bridge) ProtoReflect() protoreflect.Message {
	mi := &file_types_v2_network_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkSchemeOpts_Attrs_Bridge.ProtoReflect.Descriptor instead.
func (*NetworkSchemeOpts_Attrs_Bridge) Descriptor() ([]byte, []int) {
	return file_types_v2_network_proto_rawDescGZIP(), []int{1, 3}
}

func (x *NetworkSchemeOpts_Attrs_Bridge) GetBridgeName() string {
	if x != nil {
		return x.BridgeName
	}
	return ""
}

var File_types_v2_network_proto protoreflect.FileDescriptor

var file_types_v2_network_proto_rawDesc = []byte{
	0x0a, 0x16, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x76, 0x32, 0x2f, 0x6e, 0x65, 0x74, 0x77, 0x6f,
	0x72, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x6b, 0x76, 0x6d, 0x72, 0x75, 0x6e,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x76, 0x32, 0x22, 0xef, 0x04,
	0x0a, 0x0f, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x45, 0x6e, 0x64, 0x50, 0x6f, 0x69, 0x6e,
	0x74, 0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x69, 0x6e, 0x6b, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x69, 0x6e, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1d,
	0x0a, 0x0a, 0x6c, 0x69, 0x6e, 0x6b, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x09, 0x6c, 0x69, 0x6e, 0x6b, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x4a, 0x0a,
	0x0a, 0x76, 0x6c, 0x61, 0x6e, 0x5f, 0x61, 0x74, 0x74, 0x72, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x29, 0x2e, 0x6b, 0x76, 0x6d, 0x72, 0x75, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x74,
	0x79, 0x70, 0x65, 0x73, 0x2e, 0x76, 0x32, 0x2e, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x45,
	0x6e, 0x64, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x2e, 0x56, 0x6c, 0x61, 0x6e, 0x48, 0x00, 0x52, 0x09,
	0x76, 0x6c, 0x61, 0x6e, 0x41, 0x74, 0x74, 0x72, 0x73, 0x12, 0x4d, 0x0a, 0x0b, 0x76, 0x78, 0x6c,
	0x61, 0x6e, 0x5f, 0x61, 0x74, 0x74, 0x72, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a,
	0x2e, 0x6b, 0x76, 0x6d, 0x72, 0x75, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x74, 0x79, 0x70, 0x65,
	0x73, 0x2e, 0x76, 0x32, 0x2e, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x45, 0x6e, 0x64, 0x50,
	0x6f, 0x69, 0x6e, 0x74, 0x2e, 0x56, 0x78, 0x6c, 0x61, 0x6e, 0x48, 0x00, 0x52, 0x0a, 0x76, 0x78,
	0x6c, 0x61, 0x6e, 0x41, 0x74, 0x74, 0x72, 0x73, 0x12, 0x56, 0x0a, 0x0e, 0x69, 0x70, 0x66, 0x61,
	0x62, 0x72, 0x69, 0x63, 0x5f, 0x61, 0x74, 0x74, 0x72, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x2d, 0x2e, 0x6b, 0x76, 0x6d, 0x72, 0x75, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x74, 0x79,
	0x70, 0x65, 0x73, 0x2e, 0x76, 0x32, 0x2e, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x45, 0x6e,
	0x64, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x2e, 0x49, 0x50, 0x46, 0x61, 0x62, 0x72, 0x69, 0x63, 0x48,
	0x00, 0x52, 0x0d, 0x69, 0x70, 0x66, 0x61, 0x62, 0x72, 0x69, 0x63, 0x41, 0x74, 0x74, 0x72, 0x73,
	0x1a, 0x42, 0x0a, 0x04, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x69, 0x6e, 0x6b,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x69, 0x6e,
	0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x6c, 0x69, 0x6e, 0x6b, 0x5f, 0x69, 0x6e,
	0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x6c, 0x69, 0x6e, 0x6b, 0x49,
	0x6e, 0x64, 0x65, 0x78, 0x1a, 0x60, 0x0a, 0x04, 0x56, 0x6c, 0x61, 0x6e, 0x12, 0x17, 0x0a, 0x07,
	0x76, 0x6c, 0x61, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x76,
	0x6c, 0x61, 0x6e, 0x49, 0x64, 0x12, 0x3f, 0x0a, 0x05, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x6b, 0x76, 0x6d, 0x72, 0x75, 0x6e, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x76, 0x32, 0x2e, 0x4e, 0x65, 0x74, 0x77, 0x6f,
	0x72, 0x6b, 0x45, 0x6e, 0x64, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x2e, 0x50, 0x6f, 0x72, 0x74, 0x52,
	0x05, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x1a, 0x5a, 0x0a, 0x05, 0x56, 0x78, 0x6c, 0x61, 0x6e, 0x12,
	0x10, 0x0a, 0x03, 0x76, 0x6e, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x76, 0x6e,
	0x69, 0x12, 0x3f, 0x0a, 0x05, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x29, 0x2e, 0x6b, 0x76, 0x6d, 0x72, 0x75, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x74, 0x79,
	0x70, 0x65, 0x73, 0x2e, 0x76, 0x32, 0x2e, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x45, 0x6e,
	0x64, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x2e, 0x50, 0x6f, 0x72, 0x74, 0x52, 0x05, 0x70, 0x6f, 0x72,
	0x74, 0x73, 0x1a, 0x22, 0x0a, 0x08, 0x49, 0x50, 0x46, 0x61, 0x62, 0x72, 0x69, 0x63, 0x12, 0x16,
	0x0a, 0x06, 0x69, 0x70, 0x6e, 0x65, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06,
	0x69, 0x70, 0x6e, 0x65, 0x74, 0x73, 0x42, 0x07, 0x0a, 0x05, 0x61, 0x74, 0x74, 0x72, 0x73, 0x22,
	0xa1, 0x06, 0x0a, 0x11, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x53, 0x63, 0x68, 0x65, 0x6d,
	0x65, 0x4f, 0x70, 0x74, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x66, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x69, 0x66, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x6d, 0x74, 0x75, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6d, 0x74, 0x75, 0x12,
	0x47, 0x0a, 0x04, 0x76, 0x6c, 0x61, 0x6e, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x31, 0x2e,
	0x6b, 0x76, 0x6d, 0x72, 0x75, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73,
	0x2e, 0x76, 0x32, 0x2e, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x53, 0x63, 0x68, 0x65, 0x6d,
	0x65, 0x4f, 0x70, 0x74, 0x73, 0x2e, 0x41, 0x74, 0x74, 0x72, 0x73, 0x5f, 0x56, 0x4c, 0x41, 0x4e,
	0x48, 0x00, 0x52, 0x04, 0x76, 0x6c, 0x61, 0x6e, 0x12, 0x4a, 0x0a, 0x05, 0x76, 0x78, 0x6c, 0x61,
	0x6e, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x32, 0x2e, 0x6b, 0x76, 0x6d, 0x72, 0x75, 0x6e,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x76, 0x32, 0x2e, 0x4e, 0x65,
	0x74, 0x77, 0x6f, 0x72, 0x6b, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x65, 0x4f, 0x70, 0x74, 0x73, 0x2e,
	0x41, 0x74, 0x74, 0x72, 0x73, 0x5f, 0x56, 0x78, 0x4c, 0x41, 0x4e, 0x48, 0x00, 0x52, 0x05, 0x76,
	0x78, 0x6c, 0x61, 0x6e, 0x12, 0x4d, 0x0a, 0x06, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x18, 0x0d,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x33, 0x2e, 0x6b, 0x76, 0x6d, 0x72, 0x75, 0x6e, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x76, 0x32, 0x2e, 0x4e, 0x65, 0x74, 0x77, 0x6f,
	0x72, 0x6b, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x65, 0x4f, 0x70, 0x74, 0x73, 0x2e, 0x41, 0x74, 0x74,
	0x72, 0x73, 0x5f, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x48, 0x00, 0x52, 0x06, 0x72, 0x6f, 0x75,
	0x74, 0x65, 0x72, 0x12, 0x4d, 0x0a, 0x06, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x18, 0x0e, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x33, 0x2e, 0x6b, 0x76, 0x6d, 0x72, 0x75, 0x6e, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x76, 0x32, 0x2e, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72,
	0x6b, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x65, 0x4f, 0x70, 0x74, 0x73, 0x2e, 0x41, 0x74, 0x74, 0x72,
	0x73, 0x5f, 0x42, 0x72, 0x69, 0x64, 0x67, 0x65, 0x48, 0x00, 0x52, 0x06, 0x62, 0x72, 0x69, 0x64,
	0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x64, 0x64, 0x72, 0x73, 0x18, 0x15, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x05, 0x61, 0x64, 0x64, 0x72, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x67, 0x61, 0x74, 0x65,
	0x77, 0x61, 0x79, 0x34, 0x18, 0x16, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x67, 0x61, 0x74, 0x65,
	0x77, 0x61, 0x79, 0x34, 0x12, 0x1a, 0x0a, 0x08, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x36,
	0x18, 0x17, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x36,
	0x1a, 0x50, 0x0a, 0x0a, 0x41, 0x74, 0x74, 0x72, 0x73, 0x5f, 0x56, 0x4c, 0x41, 0x4e, 0x12, 0x17,
	0x0a, 0x07, 0x76, 0x6c, 0x61, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x06, 0x76, 0x6c, 0x61, 0x6e, 0x49, 0x64, 0x12, 0x29, 0x0a, 0x10, 0x70, 0x61, 0x72, 0x65, 0x6e,
	0x74, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0f, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61,
	0x63, 0x65, 0x1a, 0x46, 0x0a, 0x0b, 0x41, 0x74, 0x74, 0x72, 0x73, 0x5f, 0x56, 0x78, 0x4c, 0x41,
	0x4e, 0x12, 0x10, 0x0a, 0x03, 0x76, 0x6e, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03,
	0x76, 0x6e, 0x69, 0x12, 0x25, 0x0a, 0x0e, 0x62, 0x69, 0x6e, 0x64, 0x5f, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x66, 0x61, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x62, 0x69, 0x6e,
	0x64, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x1a, 0x8c, 0x01, 0x0a, 0x0c, 0x41,
	0x74, 0x74, 0x72, 0x73, 0x5f, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x12, 0x25, 0x0a, 0x0e, 0x62,
	0x69, 0x6e, 0x64, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0d, 0x62, 0x69, 0x6e, 0x64, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61,
	0x63, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x6e, 0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x69, 0x6e, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x1b, 0x0a,
	0x09, 0x6f, 0x75, 0x74, 0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x08, 0x6f, 0x75, 0x74, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72,
	0x6f, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x69, 0x64, 0x18, 0x64, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09,
	0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x49, 0x64, 0x1a, 0x2f, 0x0a, 0x0c, 0x41, 0x74, 0x74,
	0x72, 0x73, 0x5f, 0x42, 0x72, 0x69, 0x64, 0x67, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x62, 0x72, 0x69,
	0x64, 0x67, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x42, 0x07, 0x0a, 0x05, 0x61, 0x74,
	0x74, 0x72, 0x73, 0x2a, 0x56, 0x0a, 0x11, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x53, 0x63,
	0x68, 0x65, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x10, 0x55, 0x4e, 0x44, 0x45,
	0x46, 0x49, 0x4e, 0x45, 0x44, 0x5f, 0x53, 0x43, 0x48, 0x45, 0x4d, 0x45, 0x10, 0x00, 0x12, 0x0a,
	0x0a, 0x06, 0x52, 0x4f, 0x55, 0x54, 0x45, 0x44, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x42, 0x52,
	0x49, 0x44, 0x47, 0x45, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x56, 0x58, 0x4c, 0x41, 0x4e, 0x10,
	0x03, 0x12, 0x08, 0x0a, 0x04, 0x56, 0x4c, 0x41, 0x4e, 0x10, 0x04, 0x42, 0x2d, 0x5a, 0x2b, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x30, 0x78, 0x65, 0x66, 0x35, 0x33,
	0x2f, 0x6b, 0x76, 0x6d, 0x72, 0x75, 0x6e, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x74, 0x79, 0x70, 0x65,
	0x73, 0x2f, 0x76, 0x32, 0x3b, 0x74, 0x79, 0x70, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_types_v2_network_proto_rawDescOnce sync.Once
	file_types_v2_network_proto_rawDescData = file_types_v2_network_proto_rawDesc
)

func file_types_v2_network_proto_rawDescGZIP() []byte {
	file_types_v2_network_proto_rawDescOnce.Do(func() {
		file_types_v2_network_proto_rawDescData = protoimpl.X.CompressGZIP(file_types_v2_network_proto_rawDescData)
	})
	return file_types_v2_network_proto_rawDescData
}

var file_types_v2_network_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_types_v2_network_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_types_v2_network_proto_goTypes = []interface{}{
	(NetworkSchemeType)(0),                 // 0: kvmrun.api.types.v2.NetworkSchemeType
	(*NetworkEndPoint)(nil),                // 1: kvmrun.api.types.v2.NetworkEndPoint
	(*NetworkSchemeOpts)(nil),              // 2: kvmrun.api.types.v2.NetworkSchemeOpts
	(*NetworkEndPoint_Port)(nil),           // 3: kvmrun.api.types.v2.NetworkEndPoint.Port
	(*NetworkEndPoint_Vlan)(nil),           // 4: kvmrun.api.types.v2.NetworkEndPoint.Vlan
	(*NetworkEndPoint_Vxlan)(nil),          // 5: kvmrun.api.types.v2.NetworkEndPoint.Vxlan
	(*NetworkEndPoint_IPFabric)(nil),       // 6: kvmrun.api.types.v2.NetworkEndPoint.IPFabric
	(*NetworkSchemeOpts_Attrs_VLAN)(nil),   // 7: kvmrun.api.types.v2.NetworkSchemeOpts.Attrs_VLAN
	(*NetworkSchemeOpts_Attrs_VxLAN)(nil),  // 8: kvmrun.api.types.v2.NetworkSchemeOpts.Attrs_VxLAN
	(*NetworkSchemeOpts_Attrs_Router)(nil), // 9: kvmrun.api.types.v2.NetworkSchemeOpts.Attrs_Router
	(*NetworkSchemeOpts_Attrs_Bridge)(nil), // 10: kvmrun.api.types.v2.NetworkSchemeOpts.Attrs_Bridge
}
var file_types_v2_network_proto_depIdxs = []int32{
	4,  // 0: kvmrun.api.types.v2.NetworkEndPoint.vlan_attrs:type_name -> kvmrun.api.types.v2.NetworkEndPoint.Vlan
	5,  // 1: kvmrun.api.types.v2.NetworkEndPoint.vxlan_attrs:type_name -> kvmrun.api.types.v2.NetworkEndPoint.Vxlan
	6,  // 2: kvmrun.api.types.v2.NetworkEndPoint.ipfabric_attrs:type_name -> kvmrun.api.types.v2.NetworkEndPoint.IPFabric
	7,  // 3: kvmrun.api.types.v2.NetworkSchemeOpts.vlan:type_name -> kvmrun.api.types.v2.NetworkSchemeOpts.Attrs_VLAN
	8,  // 4: kvmrun.api.types.v2.NetworkSchemeOpts.vxlan:type_name -> kvmrun.api.types.v2.NetworkSchemeOpts.Attrs_VxLAN
	9,  // 5: kvmrun.api.types.v2.NetworkSchemeOpts.router:type_name -> kvmrun.api.types.v2.NetworkSchemeOpts.Attrs_Router
	10, // 6: kvmrun.api.types.v2.NetworkSchemeOpts.bridge:type_name -> kvmrun.api.types.v2.NetworkSchemeOpts.Attrs_Bridge
	3,  // 7: kvmrun.api.types.v2.NetworkEndPoint.Vlan.ports:type_name -> kvmrun.api.types.v2.NetworkEndPoint.Port
	3,  // 8: kvmrun.api.types.v2.NetworkEndPoint.Vxlan.ports:type_name -> kvmrun.api.types.v2.NetworkEndPoint.Port
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_types_v2_network_proto_init() }
func file_types_v2_network_proto_init() {
	if File_types_v2_network_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_types_v2_network_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NetworkEndPoint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_v2_network_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NetworkSchemeOpts); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_v2_network_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NetworkEndPoint_Port); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_v2_network_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NetworkEndPoint_Vlan); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_v2_network_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NetworkEndPoint_Vxlan); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_v2_network_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NetworkEndPoint_IPFabric); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_v2_network_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NetworkSchemeOpts_Attrs_VLAN); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_v2_network_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NetworkSchemeOpts_Attrs_VxLAN); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_v2_network_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NetworkSchemeOpts_Attrs_Router); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_v2_network_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NetworkSchemeOpts_Attrs_Bridge); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_types_v2_network_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*NetworkEndPoint_VlanAttrs)(nil),
		(*NetworkEndPoint_VxlanAttrs)(nil),
		(*NetworkEndPoint_IPFabricAttrs)(nil),
	}
	file_types_v2_network_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*NetworkSchemeOpts_Vlan)(nil),
		(*NetworkSchemeOpts_Vxlan)(nil),
		(*NetworkSchemeOpts_Router)(nil),
		(*NetworkSchemeOpts_Bridge)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_types_v2_network_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_v2_network_proto_goTypes,
		DependencyIndexes: file_types_v2_network_proto_depIdxs,
		EnumInfos:         file_types_v2_network_proto_enumTypes,
		MessageInfos:      file_types_v2_network_proto_msgTypes,
	}.Build()
	File_types_v2_network_proto = out.File
	file_types_v2_network_proto_rawDesc = nil
	file_types_v2_network_proto_goTypes = nil
	file_types_v2_network_proto_depIdxs = nil
}
