// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.18.3
// source: types/v2/tasks.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskInfo_TaskState int32

const (
	TaskInfo_UNKNOWN   TaskInfo_TaskState = 0
	TaskInfo_RUNNING   TaskInfo_TaskState = 1
	TaskInfo_COMPLETED TaskInfo_TaskState = 2
	TaskInfo_FAILED    TaskInfo_TaskState = 3
)

// Enum value maps for TaskInfo_TaskState.
var (
	TaskInfo_TaskState_name = map[int32]string{
		0: "UNKNOWN",
		1: "RUNNING",
		2: "COMPLETED",
		3: "FAILED",
	}
	TaskInfo_TaskState_value = map[string]int32{
		"UNKNOWN":   0,
		"RUNNING":   1,
		"COMPLETED": 2,
		"FAILED":    3,
	}
)

func (x TaskInfo_TaskState) Enum() *TaskInfo_TaskState {
	p := new(TaskInfo_TaskState)
	*p = x
	return p
}

func (x TaskInfo_TaskState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskInfo_TaskState) Descriptor() protoreflect.EnumDescriptor {
	return file_types_v2_tasks_proto_enumTypes[0].Descriptor()
}

func (TaskInfo_TaskState) Type() protoreflect.EnumType {
	return &file_types_v2_tasks_proto_enumTypes[0]
}

func (x TaskInfo_TaskState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskInfo_TaskState.Descriptor instead.
func (TaskInfo_TaskState) EnumDescriptor() ([]byte, []int) {
	return file_types_v2_tasks_proto_rawDescGZIP(), []int{0, 0}
}

type TaskInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskID    string             `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	State     TaskInfo_TaskState `protobuf:"varint,2,opt,name=state,proto3,enum=kvmrun.api.types.v2.TaskInfo_TaskState" json:"state,omitempty"`
	StateDesc string             `protobuf:"bytes,3,opt,name=state_desc,json=stateDesc,proto3" json:"state_desc,omitempty"`
	Progress  uint32             `protobuf:"varint,4,opt,name=progress,proto3" json:"progress,omitempty"`
	// Types that are assignable to Stat:
	//
	//	*TaskInfo_Migration
	Stat isTaskInfo_Stat `protobuf_oneof:"stat"`
}

func (x *TaskInfo) Reset() {
	*x = TaskInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_v2_tasks_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskInfo) ProtoMessage() {}

func (x *TaskInfo) ProtoReflect() protoreflect.Message {
	mi := &file_types_v2_tasks_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskInfo.ProtoReflect.Descriptor instead.
func (*TaskInfo) Descriptor() ([]byte, []int) {
	return file_types_v2_tasks_proto_rawDescGZIP(), []int{0}
}

func (x *TaskInfo) GetTaskID() string {
	if x != nil {
		return x.TaskID
	}
	return ""
}

func (x *TaskInfo) GetState() TaskInfo_TaskState {
	if x != nil {
		return x.State
	}
	return TaskInfo_UNKNOWN
}

func (x *TaskInfo) GetStateDesc() string {
	if x != nil {
		return x.StateDesc
	}
	return ""
}

func (x *TaskInfo) GetProgress() uint32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (m *TaskInfo) GetStat() isTaskInfo_Stat {
	if m != nil {
		return m.Stat
	}
	return nil
}

func (x *TaskInfo) GetMigration() *TaskInfo_MigrationInfo {
	if x, ok := x.GetStat().(*TaskInfo_Migration); ok {
		return x.Migration
	}
	return nil
}

type isTaskInfo_Stat interface {
	isTaskInfo_Stat()
}

type TaskInfo_Migration struct {
	Migration *TaskInfo_MigrationInfo `protobuf:"bytes,10,opt,name=migration,proto3,oneof"`
}

func (*TaskInfo_Migration) isTaskInfo_Stat() {}

type TaskInfo_MigrationInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DstServer string                                  `protobuf:"bytes,1,opt,name=dst_server,json=dstServer,proto3" json:"dst_server,omitempty"`
	Qemu      *TaskInfo_MigrationInfo_Stat            `protobuf:"bytes,2,opt,name=qemu,proto3" json:"qemu,omitempty"`
	Disks     map[string]*TaskInfo_MigrationInfo_Stat `protobuf:"bytes,3,rep,name=disks,proto3" json:"disks,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *TaskInfo_MigrationInfo) Reset() {
	*x = TaskInfo_MigrationInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_v2_tasks_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskInfo_MigrationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskInfo_MigrationInfo) ProtoMessage() {}

func (x *TaskInfo_MigrationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_types_v2_tasks_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskInfo_MigrationInfo.ProtoReflect.Descriptor instead.
func (*TaskInfo_MigrationInfo) Descriptor() ([]byte, []int) {
	return file_types_v2_tasks_proto_rawDescGZIP(), []int{0, 0}
}

func (x *TaskInfo_MigrationInfo) GetDstServer() string {
	if x != nil {
		return x.DstServer
	}
	return ""
}

func (x *TaskInfo_MigrationInfo) GetQemu() *TaskInfo_MigrationInfo_Stat {
	if x != nil {
		return x.Qemu
	}
	return nil
}

func (x *TaskInfo_MigrationInfo) GetDisks() map[string]*TaskInfo_MigrationInfo_Stat {
	if x != nil {
		return x.Disks
	}
	return nil
}

type TaskInfo_MigrationInfo_Stat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total       uint64 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Remaining   uint64 `protobuf:"varint,2,opt,name=remaining,proto3" json:"remaining,omitempty"`
	Transferred uint64 `protobuf:"varint,3,opt,name=transferred,proto3" json:"transferred,omitempty"`
	Progress    uint32 `protobuf:"varint,4,opt,name=progress,proto3" json:"progress,omitempty"`
	Speed       uint32 `protobuf:"varint,5,opt,name=speed,proto3" json:"speed,omitempty"`
}

func (x *TaskInfo_MigrationInfo_Stat) Reset() {
	*x = TaskInfo_MigrationInfo_Stat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_types_v2_tasks_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskInfo_MigrationInfo_Stat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskInfo_MigrationInfo_Stat) ProtoMessage() {}

func (x *TaskInfo_MigrationInfo_Stat) ProtoReflect() protoreflect.Message {
	mi := &file_types_v2_tasks_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskInfo_MigrationInfo_Stat.ProtoReflect.Descriptor instead.
func (*TaskInfo_MigrationInfo_Stat) Descriptor() ([]byte, []int) {
	return file_types_v2_tasks_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *TaskInfo_MigrationInfo_Stat) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *TaskInfo_MigrationInfo_Stat) GetRemaining() uint64 {
	if x != nil {
		return x.Remaining
	}
	return 0
}

func (x *TaskInfo_MigrationInfo_Stat) GetTransferred() uint64 {
	if x != nil {
		return x.Transferred
	}
	return 0
}

func (x *TaskInfo_MigrationInfo_Stat) GetProgress() uint32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *TaskInfo_MigrationInfo_Stat) GetSpeed() uint32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

var File_types_v2_tasks_proto protoreflect.FileDescriptor

var file_types_v2_tasks_proto_rawDesc = []byte{
	0x0a, 0x14, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x76, 0x32, 0x2f, 0x74, 0x61, 0x73, 0x6b, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x6b, 0x76, 0x6d, 0x72, 0x75, 0x6e, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x76, 0x32, 0x22, 0xf6, 0x05, 0x0a, 0x08,
	0x54, 0x61, 0x73, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x61, 0x73, 0x6b,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49,
	0x64, 0x12, 0x3d, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x27, 0x2e, 0x6b, 0x76, 0x6d, 0x72, 0x75, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x74, 0x79,
	0x70, 0x65, 0x73, 0x2e, 0x76, 0x32, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x2e,
	0x54, 0x61, 0x73, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65,
	0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x65, 0x5f, 0x64, 0x65, 0x73, 0x63, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x61, 0x74, 0x65, 0x44, 0x65, 0x73, 0x63, 0x12,
	0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x12, 0x4b, 0x0a, 0x09, 0x6d,
	0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2b,
	0x2e, 0x6b, 0x76, 0x6d, 0x72, 0x75, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x74, 0x79, 0x70, 0x65,
	0x73, 0x2e, 0x76, 0x32, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x4d, 0x69,
	0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x48, 0x00, 0x52, 0x09, 0x6d,
	0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0xbf, 0x03, 0x0a, 0x0d, 0x4d, 0x69, 0x67,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1d, 0x0a, 0x0a, 0x64, 0x73,
	0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x64, 0x73, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x44, 0x0a, 0x04, 0x71, 0x65, 0x6d,
	0x75, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x30, 0x2e, 0x6b, 0x76, 0x6d, 0x72, 0x75, 0x6e,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x76, 0x32, 0x2e, 0x54, 0x61,
	0x73, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x52, 0x04, 0x71, 0x65, 0x6d, 0x75, 0x12,
	0x4c, 0x0a, 0x05, 0x64, 0x69, 0x73, 0x6b, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x36,
	0x2e, 0x6b, 0x76, 0x6d, 0x72, 0x75, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x74, 0x79, 0x70, 0x65,
	0x73, 0x2e, 0x76, 0x32, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x4d, 0x69,
	0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x44, 0x69, 0x73, 0x6b,
	0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x64, 0x69, 0x73, 0x6b, 0x73, 0x1a, 0x8e, 0x01,
	0x0a, 0x04, 0x53, 0x74, 0x61, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x1c, 0x0a, 0x09,
	0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x09, 0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x72,
	0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x72, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x72, 0x65, 0x64, 0x12, 0x1a, 0x0a, 0x08,
	0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08,
	0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x70, 0x65, 0x65,
	0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x73, 0x70, 0x65, 0x65, 0x64, 0x1a, 0x6a,
	0x0a, 0x0a, 0x44, 0x69, 0x73, 0x6b, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x46,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x30, 0x2e,
	0x6b, 0x76, 0x6d, 0x72, 0x75, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73,
	0x2e, 0x76, 0x32, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x4d, 0x69, 0x67,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x40, 0x0a, 0x09, 0x54, 0x61,
	0x73, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f,
	0x57, 0x4e, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x52, 0x55, 0x4e, 0x4e, 0x49, 0x4e, 0x47, 0x10,
	0x01, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x4f, 0x4d, 0x50, 0x4c, 0x45, 0x54, 0x45, 0x44, 0x10, 0x02,
	0x12, 0x0a, 0x0a, 0x06, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x03, 0x42, 0x06, 0x0a, 0x04,
	0x73, 0x74, 0x61, 0x74, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x30, 0x78, 0x65, 0x66, 0x35, 0x33, 0x2f, 0x6b, 0x76, 0x6d, 0x72, 0x75, 0x6e,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x76, 0x32, 0x3b, 0x74, 0x79,
	0x70, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_types_v2_tasks_proto_rawDescOnce sync.Once
	file_types_v2_tasks_proto_rawDescData = file_types_v2_tasks_proto_rawDesc
)

func file_types_v2_tasks_proto_rawDescGZIP() []byte {
	file_types_v2_tasks_proto_rawDescOnce.Do(func() {
		file_types_v2_tasks_proto_rawDescData = protoimpl.X.CompressGZIP(file_types_v2_tasks_proto_rawDescData)
	})
	return file_types_v2_tasks_proto_rawDescData
}

var file_types_v2_tasks_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_types_v2_tasks_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_types_v2_tasks_proto_goTypes = []interface{}{
	(TaskInfo_TaskState)(0),             // 0: kvmrun.api.types.v2.TaskInfo.TaskState
	(*TaskInfo)(nil),                    // 1: kvmrun.api.types.v2.TaskInfo
	(*TaskInfo_MigrationInfo)(nil),      // 2: kvmrun.api.types.v2.TaskInfo.MigrationInfo
	(*TaskInfo_MigrationInfo_Stat)(nil), // 3: kvmrun.api.types.v2.TaskInfo.MigrationInfo.Stat
	nil,                                 // 4: kvmrun.api.types.v2.TaskInfo.MigrationInfo.DisksEntry
}
var file_types_v2_tasks_proto_depIdxs = []int32{
	0, // 0: kvmrun.api.types.v2.TaskInfo.state:type_name -> kvmrun.api.types.v2.TaskInfo.TaskState
	2, // 1: kvmrun.api.types.v2.TaskInfo.migration:type_name -> kvmrun.api.types.v2.TaskInfo.MigrationInfo
	3, // 2: kvmrun.api.types.v2.TaskInfo.MigrationInfo.qemu:type_name -> kvmrun.api.types.v2.TaskInfo.MigrationInfo.Stat
	4, // 3: kvmrun.api.types.v2.TaskInfo.MigrationInfo.disks:type_name -> kvmrun.api.types.v2.TaskInfo.MigrationInfo.DisksEntry
	3, // 4: kvmrun.api.types.v2.TaskInfo.MigrationInfo.DisksEntry.value:type_name -> kvmrun.api.types.v2.TaskInfo.MigrationInfo.Stat
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_types_v2_tasks_proto_init() }
func file_types_v2_tasks_proto_init() {
	if File_types_v2_tasks_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_types_v2_tasks_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_v2_tasks_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskInfo_MigrationInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_types_v2_tasks_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskInfo_MigrationInfo_Stat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_types_v2_tasks_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*TaskInfo_Migration)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_types_v2_tasks_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_v2_tasks_proto_goTypes,
		DependencyIndexes: file_types_v2_tasks_proto_depIdxs,
		EnumInfos:         file_types_v2_tasks_proto_enumTypes,
		MessageInfos:      file_types_v2_tasks_proto_msgTypes,
	}.Build()
	File_types_v2_tasks_proto = out.File
	file_types_v2_tasks_proto_rawDesc = nil
	file_types_v2_tasks_proto_goTypes = nil
	file_types_v2_tasks_proto_depIdxs = nil
}
