package task

// TaskState represents the possible states of a task
type TaskState uint32

const (
	StateUnknown TaskState = iota
	StateRunning
	StateCompleted
	StateFailed
)

// TaskStat contains summary information about the current task state.
type TaskStat struct {
	ID          string    `json:"id"`
	ShortID     string    `json:"short_id"`
	State       TaskState `json:"state"`
	StateDesc   string    `json:"state_desc"`
	Interrupted bool      `json:"interrupted"`
	Progress    int       `json:"progress"`

	// Details contains arbitrary additional stat information
	// generated by the task code during execution.
	Details interface{} `json:"details"`

	// Metadata contains optional user-defined info extracted from the context.
	// If not specified, the value will be nil.
	Metadata interface{} `json:"metadata"`
}
