// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.18.3
// source: services/system/v2/system.proto

package system

import (
	context "context"
	_ "github.com/0xef53/go-grpc/options"
	v2 "github.com/0xef53/kvmrun/api/types/v2"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QemuInstanceRegisterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	MemActual uint32 `protobuf:"varint,2,opt,name=mem_actual,json=memActual,proto3" json:"mem_actual,omitempty"`
	PID       uint32 `protobuf:"varint,3,opt,name=pid,proto3" json:"pid,omitempty"`
}

func (x *QemuInstanceRegisterRequest) Reset() {
	*x = QemuInstanceRegisterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_system_v2_system_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QemuInstanceRegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QemuInstanceRegisterRequest) ProtoMessage() {}

func (x *QemuInstanceRegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_system_v2_system_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QemuInstanceRegisterRequest.ProtoReflect.Descriptor instead.
func (*QemuInstanceRegisterRequest) Descriptor() ([]byte, []int) {
	return file_services_system_v2_system_proto_rawDescGZIP(), []int{0}
}

func (x *QemuInstanceRegisterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *QemuInstanceRegisterRequest) GetMemActual() uint32 {
	if x != nil {
		return x.MemActual
	}
	return 0
}

func (x *QemuInstanceRegisterRequest) GetPID() uint32 {
	if x != nil {
		return x.PID
	}
	return 0
}

type QemuInstanceDeregisterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *QemuInstanceDeregisterRequest) Reset() {
	*x = QemuInstanceDeregisterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_system_v2_system_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QemuInstanceDeregisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QemuInstanceDeregisterRequest) ProtoMessage() {}

func (x *QemuInstanceDeregisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_system_v2_system_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QemuInstanceDeregisterRequest.ProtoReflect.Descriptor instead.
func (*QemuInstanceDeregisterRequest) Descriptor() ([]byte, []int) {
	return file_services_system_v2_system_proto_rawDescGZIP(), []int{1}
}

func (x *QemuInstanceDeregisterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type QemuInstanceStopRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name            string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	GracefulTimeout uint32 `protobuf:"varint,2,opt,name=graceful_timeout,json=gracefulTimeout,proto3" json:"graceful_timeout,omitempty"`
}

func (x *QemuInstanceStopRequest) Reset() {
	*x = QemuInstanceStopRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_system_v2_system_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QemuInstanceStopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QemuInstanceStopRequest) ProtoMessage() {}

func (x *QemuInstanceStopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_system_v2_system_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QemuInstanceStopRequest.ProtoReflect.Descriptor instead.
func (*QemuInstanceStopRequest) Descriptor() ([]byte, []int) {
	return file_services_system_v2_system_proto_rawDescGZIP(), []int{2}
}

func (x *QemuInstanceStopRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *QemuInstanceStopRequest) GetGracefulTimeout() uint32 {
	if x != nil {
		return x.GracefulTimeout
	}
	return 0
}

type StartIncomingMigrationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name         string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Manifest     []byte            `protobuf:"bytes,2,opt,name=manifest,proto3" json:"manifest,omitempty"`
	Disks        map[string]uint64 `protobuf:"bytes,3,rep,name=disks,proto3" json:"disks,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	ExtraFiles   map[string][]byte `protobuf:"bytes,4,rep,name=extra_files,json=extraFiles,proto3" json:"extra_files,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	CreateDisks  bool              `protobuf:"varint,5,opt,name=create_disks,json=createDisks,proto3" json:"create_disks,omitempty"`
	ListenAddr   string            `protobuf:"bytes,6,opt,name=listen_addr,json=listenAddr,proto3" json:"listen_addr,omitempty"`
	TurnOffAfter bool              `protobuf:"varint,7,opt,name=turn_off_after,json=turnOffAfter,proto3" json:"turn_off_after,omitempty"`
}

func (x *StartIncomingMigrationRequest) Reset() {
	*x = StartIncomingMigrationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_system_v2_system_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartIncomingMigrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartIncomingMigrationRequest) ProtoMessage() {}

func (x *StartIncomingMigrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_system_v2_system_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartIncomingMigrationRequest.ProtoReflect.Descriptor instead.
func (*StartIncomingMigrationRequest) Descriptor() ([]byte, []int) {
	return file_services_system_v2_system_proto_rawDescGZIP(), []int{3}
}

func (x *StartIncomingMigrationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StartIncomingMigrationRequest) GetManifest() []byte {
	if x != nil {
		return x.Manifest
	}
	return nil
}

func (x *StartIncomingMigrationRequest) GetDisks() map[string]uint64 {
	if x != nil {
		return x.Disks
	}
	return nil
}

func (x *StartIncomingMigrationRequest) GetExtraFiles() map[string][]byte {
	if x != nil {
		return x.ExtraFiles
	}
	return nil
}

func (x *StartIncomingMigrationRequest) GetCreateDisks() bool {
	if x != nil {
		return x.CreateDisks
	}
	return false
}

func (x *StartIncomingMigrationRequest) GetListenAddr() string {
	if x != nil {
		return x.ListenAddr
	}
	return ""
}

func (x *StartIncomingMigrationRequest) GetTurnOffAfter() bool {
	if x != nil {
		return x.TurnOffAfter
	}
	return false
}

type StartIncomingMigrationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Requisites *v2.IncomingMigrationRequisites `protobuf:"bytes,1,opt,name=requisites,proto3" json:"requisites,omitempty"`
}

func (x *StartIncomingMigrationResponse) Reset() {
	*x = StartIncomingMigrationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_system_v2_system_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartIncomingMigrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartIncomingMigrationResponse) ProtoMessage() {}

func (x *StartIncomingMigrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_system_v2_system_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartIncomingMigrationResponse.ProtoReflect.Descriptor instead.
func (*StartIncomingMigrationResponse) Descriptor() ([]byte, []int) {
	return file_services_system_v2_system_proto_rawDescGZIP(), []int{4}
}

func (x *StartIncomingMigrationResponse) GetRequisites() *v2.IncomingMigrationRequisites {
	if x != nil {
		return x.Requisites
	}
	return nil
}

type GetAppConfResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppConf *v2.AppConf `protobuf:"bytes,1,opt,name=app_conf,json=appConf,proto3" json:"app_conf,omitempty"`
}

func (x *GetAppConfResponse) Reset() {
	*x = GetAppConfResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_system_v2_system_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAppConfResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppConfResponse) ProtoMessage() {}

func (x *GetAppConfResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_system_v2_system_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppConfResponse.ProtoReflect.Descriptor instead.
func (*GetAppConfResponse) Descriptor() ([]byte, []int) {
	return file_services_system_v2_system_proto_rawDescGZIP(), []int{5}
}

func (x *GetAppConfResponse) GetAppConf() *v2.AppConf {
	if x != nil {
		return x.AppConf
	}
	return nil
}

var File_services_system_v2_system_proto protoreflect.FileDescriptor

var file_services_system_v2_system_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x73, 0x79, 0x73, 0x74, 0x65,
	0x6d, 0x2f, 0x76, 0x32, 0x2f, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x1d, 0x6b, 0x76, 0x6d, 0x72, 0x75, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x2e, 0x76, 0x32,
	0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x15, 0x74,
	0x79, 0x70, 0x65, 0x73, 0x2f, 0x76, 0x32, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x76, 0x32, 0x2f, 0x6d,
	0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x35, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x30, 0x78, 0x65, 0x66, 0x35, 0x33,
	0x2f, 0x67, 0x6f, 0x2d, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x2f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x62, 0x0a, 0x1b, 0x51, 0x65, 0x6d, 0x75, 0x49, 0x6e, 0x73, 0x74,
	0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x65, 0x6d, 0x5f, 0x61,
	0x63, 0x74, 0x75, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x6d, 0x65, 0x6d,
	0x41, 0x63, 0x74, 0x75, 0x61, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x03, 0x70, 0x69, 0x64, 0x22, 0x33, 0x0a, 0x1d, 0x51, 0x65, 0x6d, 0x75,
	0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x44, 0x65, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x58, 0x0a,
	0x17, 0x51, 0x65, 0x6d, 0x75, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x53, 0x74, 0x6f,
	0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x29, 0x0a, 0x10,
	0x67, 0x72, 0x61, 0x63, 0x65, 0x66, 0x75, 0x6c, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0f, 0x67, 0x72, 0x61, 0x63, 0x65, 0x66, 0x75, 0x6c,
	0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x22, 0x90, 0x04, 0x0a, 0x1d, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x49, 0x6e, 0x63, 0x6f, 0x6d, 0x69, 0x6e, 0x67, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x22, 0x0a,
	0x08, 0x6d, 0x61, 0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x42,
	0x06, 0xca, 0xed, 0x1a, 0x02, 0x08, 0x01, 0x52, 0x08, 0x6d, 0x61, 0x6e, 0x69, 0x66, 0x65, 0x73,
	0x74, 0x12, 0x5d, 0x0a, 0x05, 0x64, 0x69, 0x73, 0x6b, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x47, 0x2e, 0x6b, 0x76, 0x6d, 0x72, 0x75, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x2e, 0x76, 0x32,
	0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x49, 0x6e, 0x63, 0x6f, 0x6d, 0x69, 0x6e, 0x67, 0x4d, 0x69,
	0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x44,
	0x69, 0x73, 0x6b, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x64, 0x69, 0x73, 0x6b, 0x73,
	0x12, 0x75, 0x0a, 0x0b, 0x65, 0x78, 0x74, 0x72, 0x61, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x18,
	0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x4c, 0x2e, 0x6b, 0x76, 0x6d, 0x72, 0x75, 0x6e, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x73, 0x79, 0x73, 0x74,
	0x65, 0x6d, 0x2e, 0x76, 0x32, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x49, 0x6e, 0x63, 0x6f, 0x6d,
	0x69, 0x6e, 0x67, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x2e, 0x45, 0x78, 0x74, 0x72, 0x61, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x42, 0x06, 0xca, 0xed, 0x1a, 0x02, 0x08, 0x01, 0x52, 0x0a, 0x65, 0x78, 0x74,
	0x72, 0x61, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x5f, 0x64, 0x69, 0x73, 0x6b, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x69, 0x73, 0x6b, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x6c, 0x69,
	0x73, 0x74, 0x65, 0x6e, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x6c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x41, 0x64, 0x64, 0x72, 0x12, 0x24, 0x0a, 0x0e, 0x74,
	0x75, 0x72, 0x6e, 0x5f, 0x6f, 0x66, 0x66, 0x5f, 0x61, 0x66, 0x74, 0x65, 0x72, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x0c, 0x74, 0x75, 0x72, 0x6e, 0x4f, 0x66, 0x66, 0x41, 0x66, 0x74, 0x65,
	0x72, 0x1a, 0x38, 0x0a, 0x0a, 0x44, 0x69, 0x73, 0x6b, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a, 0x3d, 0x0a, 0x0f, 0x45,
	0x78, 0x74, 0x72, 0x61, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x72, 0x0a, 0x1e, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x49, 0x6e, 0x63, 0x6f, 0x6d, 0x69, 0x6e, 0x67, 0x4d, 0x69, 0x67, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x50, 0x0a, 0x0a,
	0x72, 0x65, 0x71, 0x75, 0x69, 0x73, 0x69, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x30, 0x2e, 0x6b, 0x76, 0x6d, 0x72, 0x75, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x74, 0x79,
	0x70, 0x65, 0x73, 0x2e, 0x76, 0x32, 0x2e, 0x49, 0x6e, 0x63, 0x6f, 0x6d, 0x69, 0x6e, 0x67, 0x4d,
	0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x69, 0x73, 0x69, 0x74,
	0x65, 0x73, 0x52, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x69, 0x73, 0x69, 0x74, 0x65, 0x73, 0x22, 0x4d,
	0x0a, 0x12, 0x47, 0x65, 0x74, 0x41, 0x70, 0x70, 0x43, 0x6f, 0x6e, 0x66, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x37, 0x0a, 0x08, 0x61, 0x70, 0x70, 0x5f, 0x63, 0x6f, 0x6e, 0x66,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6b, 0x76, 0x6d, 0x72, 0x75, 0x6e, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x76, 0x32, 0x2e, 0x41, 0x70, 0x70,
	0x43, 0x6f, 0x6e, 0x66, 0x52, 0x07, 0x61, 0x70, 0x70, 0x43, 0x6f, 0x6e, 0x66, 0x32, 0x96, 0x05,
	0x0a, 0x0d, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x6c, 0x0a, 0x14, 0x51, 0x65, 0x6d, 0x75, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x12, 0x3a, 0x2e, 0x6b, 0x76, 0x6d, 0x72, 0x75, 0x6e,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x73, 0x79,
	0x73, 0x74, 0x65, 0x6d, 0x2e, 0x76, 0x32, 0x2e, 0x51, 0x65, 0x6d, 0x75, 0x49, 0x6e, 0x73, 0x74,
	0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x70, 0x0a,
	0x16, 0x51, 0x65, 0x6d, 0x75, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x44, 0x65, 0x72,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x12, 0x3c, 0x2e, 0x6b, 0x76, 0x6d, 0x72, 0x75, 0x6e,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x73, 0x79,
	0x73, 0x74, 0x65, 0x6d, 0x2e, 0x76, 0x32, 0x2e, 0x51, 0x65, 0x6d, 0x75, 0x49, 0x6e, 0x73, 0x74,
	0x61, 0x6e, 0x63, 0x65, 0x44, 0x65, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12,
	0x64, 0x0a, 0x10, 0x51, 0x65, 0x6d, 0x75, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x53,
	0x74, 0x6f, 0x70, 0x12, 0x36, 0x2e, 0x6b, 0x76, 0x6d, 0x72, 0x75, 0x6e, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d,
	0x2e, 0x76, 0x32, 0x2e, 0x51, 0x65, 0x6d, 0x75, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65,
	0x53, 0x74, 0x6f, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x97, 0x01, 0x0a, 0x16, 0x53, 0x74, 0x61, 0x72, 0x74, 0x49,
	0x6e, 0x63, 0x6f, 0x6d, 0x69, 0x6e, 0x67, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x3c, 0x2e, 0x6b, 0x76, 0x6d, 0x72, 0x75, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x2e, 0x76, 0x32,
	0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x49, 0x6e, 0x63, 0x6f, 0x6d, 0x69, 0x6e, 0x67, 0x4d, 0x69,
	0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x3d,
	0x2e, 0x6b, 0x76, 0x6d, 0x72, 0x75, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x73, 0x2e, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x2e, 0x76, 0x32, 0x2e, 0x53,
	0x74, 0x61, 0x72, 0x74, 0x49, 0x6e, 0x63, 0x6f, 0x6d, 0x69, 0x6e, 0x67, 0x4d, 0x69, 0x67, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x4a, 0x0a, 0x16, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x47, 0x72, 0x61, 0x63, 0x65, 0x66, 0x75,
	0x6c, 0x53, 0x68, 0x75, 0x74, 0x64, 0x6f, 0x77, 0x6e, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x59, 0x0a, 0x0a, 0x47,
	0x65, 0x74, 0x41, 0x70, 0x70, 0x43, 0x6f, 0x6e, 0x66, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x1a, 0x31, 0x2e, 0x6b, 0x76, 0x6d, 0x72, 0x75, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x2e, 0x76,
	0x32, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x70, 0x70, 0x43, 0x6f, 0x6e, 0x66, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x38, 0x5a, 0x36, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x30, 0x78, 0x65, 0x66, 0x35, 0x33, 0x2f, 0x6b, 0x76, 0x6d, 0x72,
	0x75, 0x6e, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f,
	0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x2f, 0x76, 0x32, 0x3b, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_services_system_v2_system_proto_rawDescOnce sync.Once
	file_services_system_v2_system_proto_rawDescData = file_services_system_v2_system_proto_rawDesc
)

func file_services_system_v2_system_proto_rawDescGZIP() []byte {
	file_services_system_v2_system_proto_rawDescOnce.Do(func() {
		file_services_system_v2_system_proto_rawDescData = protoimpl.X.CompressGZIP(file_services_system_v2_system_proto_rawDescData)
	})
	return file_services_system_v2_system_proto_rawDescData
}

var file_services_system_v2_system_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_services_system_v2_system_proto_goTypes = []interface{}{
	(*QemuInstanceRegisterRequest)(nil),    // 0: kvmrun.api.services.system.v2.QemuInstanceRegisterRequest
	(*QemuInstanceDeregisterRequest)(nil),  // 1: kvmrun.api.services.system.v2.QemuInstanceDeregisterRequest
	(*QemuInstanceStopRequest)(nil),        // 2: kvmrun.api.services.system.v2.QemuInstanceStopRequest
	(*StartIncomingMigrationRequest)(nil),  // 3: kvmrun.api.services.system.v2.StartIncomingMigrationRequest
	(*StartIncomingMigrationResponse)(nil), // 4: kvmrun.api.services.system.v2.StartIncomingMigrationResponse
	(*GetAppConfResponse)(nil),             // 5: kvmrun.api.services.system.v2.GetAppConfResponse
	nil,                                    // 6: kvmrun.api.services.system.v2.StartIncomingMigrationRequest.DisksEntry
	nil,                                    // 7: kvmrun.api.services.system.v2.StartIncomingMigrationRequest.ExtraFilesEntry
	(*v2.IncomingMigrationRequisites)(nil), // 8: kvmrun.api.types.v2.IncomingMigrationRequisites
	(*v2.AppConf)(nil),                     // 9: kvmrun.api.types.v2.AppConf
	(*emptypb.Empty)(nil),                  // 10: google.protobuf.Empty
}
var file_services_system_v2_system_proto_depIdxs = []int32{
	6,  // 0: kvmrun.api.services.system.v2.StartIncomingMigrationRequest.disks:type_name -> kvmrun.api.services.system.v2.StartIncomingMigrationRequest.DisksEntry
	7,  // 1: kvmrun.api.services.system.v2.StartIncomingMigrationRequest.extra_files:type_name -> kvmrun.api.services.system.v2.StartIncomingMigrationRequest.ExtraFilesEntry
	8,  // 2: kvmrun.api.services.system.v2.StartIncomingMigrationResponse.requisites:type_name -> kvmrun.api.types.v2.IncomingMigrationRequisites
	9,  // 3: kvmrun.api.services.system.v2.GetAppConfResponse.app_conf:type_name -> kvmrun.api.types.v2.AppConf
	0,  // 4: kvmrun.api.services.system.v2.SystemService.QemuInstanceRegister:input_type -> kvmrun.api.services.system.v2.QemuInstanceRegisterRequest
	1,  // 5: kvmrun.api.services.system.v2.SystemService.QemuInstanceDeregister:input_type -> kvmrun.api.services.system.v2.QemuInstanceDeregisterRequest
	2,  // 6: kvmrun.api.services.system.v2.SystemService.QemuInstanceStop:input_type -> kvmrun.api.services.system.v2.QemuInstanceStopRequest
	3,  // 7: kvmrun.api.services.system.v2.SystemService.StartIncomingMigration:input_type -> kvmrun.api.services.system.v2.StartIncomingMigrationRequest
	10, // 8: kvmrun.api.services.system.v2.SystemService.ServerGracefulShutdown:input_type -> google.protobuf.Empty
	10, // 9: kvmrun.api.services.system.v2.SystemService.GetAppConf:input_type -> google.protobuf.Empty
	10, // 10: kvmrun.api.services.system.v2.SystemService.QemuInstanceRegister:output_type -> google.protobuf.Empty
	10, // 11: kvmrun.api.services.system.v2.SystemService.QemuInstanceDeregister:output_type -> google.protobuf.Empty
	10, // 12: kvmrun.api.services.system.v2.SystemService.QemuInstanceStop:output_type -> google.protobuf.Empty
	4,  // 13: kvmrun.api.services.system.v2.SystemService.StartIncomingMigration:output_type -> kvmrun.api.services.system.v2.StartIncomingMigrationResponse
	10, // 14: kvmrun.api.services.system.v2.SystemService.ServerGracefulShutdown:output_type -> google.protobuf.Empty
	5,  // 15: kvmrun.api.services.system.v2.SystemService.GetAppConf:output_type -> kvmrun.api.services.system.v2.GetAppConfResponse
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_services_system_v2_system_proto_init() }
func file_services_system_v2_system_proto_init() {
	if File_services_system_v2_system_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_services_system_v2_system_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QemuInstanceRegisterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_system_v2_system_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QemuInstanceDeregisterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_system_v2_system_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QemuInstanceStopRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_system_v2_system_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartIncomingMigrationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_system_v2_system_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartIncomingMigrationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_system_v2_system_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAppConfResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_services_system_v2_system_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_system_v2_system_proto_goTypes,
		DependencyIndexes: file_services_system_v2_system_proto_depIdxs,
		MessageInfos:      file_services_system_v2_system_proto_msgTypes,
	}.Build()
	File_services_system_v2_system_proto = out.File
	file_services_system_v2_system_proto_rawDesc = nil
	file_services_system_v2_system_proto_goTypes = nil
	file_services_system_v2_system_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SystemServiceClient is the client API for SystemService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SystemServiceClient interface {
	QemuInstanceRegister(ctx context.Context, in *QemuInstanceRegisterRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	QemuInstanceDeregister(ctx context.Context, in *QemuInstanceDeregisterRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	QemuInstanceStop(ctx context.Context, in *QemuInstanceStopRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	StartIncomingMigration(ctx context.Context, in *StartIncomingMigrationRequest, opts ...grpc.CallOption) (*StartIncomingMigrationResponse, error)
	ServerGracefulShutdown(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetAppConf(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetAppConfResponse, error)
}

type systemServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSystemServiceClient(cc grpc.ClientConnInterface) SystemServiceClient {
	return &systemServiceClient{cc}
}

func (c *systemServiceClient) QemuInstanceRegister(ctx context.Context, in *QemuInstanceRegisterRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/kvmrun.api.services.system.v2.SystemService/QemuInstanceRegister", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemServiceClient) QemuInstanceDeregister(ctx context.Context, in *QemuInstanceDeregisterRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/kvmrun.api.services.system.v2.SystemService/QemuInstanceDeregister", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemServiceClient) QemuInstanceStop(ctx context.Context, in *QemuInstanceStopRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/kvmrun.api.services.system.v2.SystemService/QemuInstanceStop", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemServiceClient) StartIncomingMigration(ctx context.Context, in *StartIncomingMigrationRequest, opts ...grpc.CallOption) (*StartIncomingMigrationResponse, error) {
	out := new(StartIncomingMigrationResponse)
	err := c.cc.Invoke(ctx, "/kvmrun.api.services.system.v2.SystemService/StartIncomingMigration", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemServiceClient) ServerGracefulShutdown(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/kvmrun.api.services.system.v2.SystemService/ServerGracefulShutdown", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemServiceClient) GetAppConf(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetAppConfResponse, error) {
	out := new(GetAppConfResponse)
	err := c.cc.Invoke(ctx, "/kvmrun.api.services.system.v2.SystemService/GetAppConf", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SystemServiceServer is the server API for SystemService service.
type SystemServiceServer interface {
	QemuInstanceRegister(context.Context, *QemuInstanceRegisterRequest) (*emptypb.Empty, error)
	QemuInstanceDeregister(context.Context, *QemuInstanceDeregisterRequest) (*emptypb.Empty, error)
	QemuInstanceStop(context.Context, *QemuInstanceStopRequest) (*emptypb.Empty, error)
	StartIncomingMigration(context.Context, *StartIncomingMigrationRequest) (*StartIncomingMigrationResponse, error)
	ServerGracefulShutdown(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	GetAppConf(context.Context, *emptypb.Empty) (*GetAppConfResponse, error)
}

// UnimplementedSystemServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSystemServiceServer struct {
}

func (*UnimplementedSystemServiceServer) QemuInstanceRegister(context.Context, *QemuInstanceRegisterRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QemuInstanceRegister not implemented")
}
func (*UnimplementedSystemServiceServer) QemuInstanceDeregister(context.Context, *QemuInstanceDeregisterRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QemuInstanceDeregister not implemented")
}
func (*UnimplementedSystemServiceServer) QemuInstanceStop(context.Context, *QemuInstanceStopRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QemuInstanceStop not implemented")
}
func (*UnimplementedSystemServiceServer) StartIncomingMigration(context.Context, *StartIncomingMigrationRequest) (*StartIncomingMigrationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartIncomingMigration not implemented")
}
func (*UnimplementedSystemServiceServer) ServerGracefulShutdown(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ServerGracefulShutdown not implemented")
}
func (*UnimplementedSystemServiceServer) GetAppConf(context.Context, *emptypb.Empty) (*GetAppConfResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAppConf not implemented")
}

func RegisterSystemServiceServer(s *grpc.Server, srv SystemServiceServer) {
	s.RegisterService(&_SystemService_serviceDesc, srv)
}

func _SystemService_QemuInstanceRegister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QemuInstanceRegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).QemuInstanceRegister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kvmrun.api.services.system.v2.SystemService/QemuInstanceRegister",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).QemuInstanceRegister(ctx, req.(*QemuInstanceRegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemService_QemuInstanceDeregister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QemuInstanceDeregisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).QemuInstanceDeregister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kvmrun.api.services.system.v2.SystemService/QemuInstanceDeregister",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).QemuInstanceDeregister(ctx, req.(*QemuInstanceDeregisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemService_QemuInstanceStop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QemuInstanceStopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).QemuInstanceStop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kvmrun.api.services.system.v2.SystemService/QemuInstanceStop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).QemuInstanceStop(ctx, req.(*QemuInstanceStopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemService_StartIncomingMigration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartIncomingMigrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).StartIncomingMigration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kvmrun.api.services.system.v2.SystemService/StartIncomingMigration",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).StartIncomingMigration(ctx, req.(*StartIncomingMigrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemService_ServerGracefulShutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).ServerGracefulShutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kvmrun.api.services.system.v2.SystemService/ServerGracefulShutdown",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).ServerGracefulShutdown(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemService_GetAppConf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).GetAppConf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kvmrun.api.services.system.v2.SystemService/GetAppConf",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).GetAppConf(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _SystemService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kvmrun.api.services.system.v2.SystemService",
	HandlerType: (*SystemServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QemuInstanceRegister",
			Handler:    _SystemService_QemuInstanceRegister_Handler,
		},
		{
			MethodName: "QemuInstanceDeregister",
			Handler:    _SystemService_QemuInstanceDeregister_Handler,
		},
		{
			MethodName: "QemuInstanceStop",
			Handler:    _SystemService_QemuInstanceStop_Handler,
		},
		{
			MethodName: "StartIncomingMigration",
			Handler:    _SystemService_StartIncomingMigration_Handler,
		},
		{
			MethodName: "ServerGracefulShutdown",
			Handler:    _SystemService_ServerGracefulShutdown_Handler,
		},
		{
			MethodName: "GetAppConf",
			Handler:    _SystemService_GetAppConf_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/system/v2/system.proto",
}
