// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.18.3
// source: services/network/v2/network.proto

package network

import (
	context "context"
	v2 "github.com/0xef53/kvmrun/api/types/v2"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateConfRequest_Addr_Action int32

const (
	UpdateConfRequest_Addr_UNKNOWN UpdateConfRequest_Addr_Action = 0
	UpdateConfRequest_Addr_APPEND  UpdateConfRequest_Addr_Action = 1
	UpdateConfRequest_Addr_REMOVE  UpdateConfRequest_Addr_Action = 2
)

// Enum value maps for UpdateConfRequest_Addr_Action.
var (
	UpdateConfRequest_Addr_Action_name = map[int32]string{
		0: "UNKNOWN",
		1: "APPEND",
		2: "REMOVE",
	}
	UpdateConfRequest_Addr_Action_value = map[string]int32{
		"UNKNOWN": 0,
		"APPEND":  1,
		"REMOVE":  2,
	}
)

func (x UpdateConfRequest_Addr_Action) Enum() *UpdateConfRequest_Addr_Action {
	p := new(UpdateConfRequest_Addr_Action)
	*p = x
	return p
}

func (x UpdateConfRequest_Addr_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UpdateConfRequest_Addr_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_services_network_v2_network_proto_enumTypes[0].Descriptor()
}

func (UpdateConfRequest_Addr_Action) Type() protoreflect.EnumType {
	return &file_services_network_v2_network_proto_enumTypes[0]
}

func (x UpdateConfRequest_Addr_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UpdateConfRequest_Addr_Action.Descriptor instead.
func (UpdateConfRequest_Addr_Action) EnumDescriptor() ([]byte, []int) {
	return file_services_network_v2_network_proto_rawDescGZIP(), []int{5, 0, 0}
}

type ListEndpointsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filter *ListEndpointsRequest_Filter `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
}

func (x *ListEndpointsRequest) Reset() {
	*x = ListEndpointsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_network_v2_network_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListEndpointsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEndpointsRequest) ProtoMessage() {}

func (x *ListEndpointsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_network_v2_network_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEndpointsRequest.ProtoReflect.Descriptor instead.
func (*ListEndpointsRequest) Descriptor() ([]byte, []int) {
	return file_services_network_v2_network_proto_rawDescGZIP(), []int{0}
}

func (x *ListEndpointsRequest) GetFilter() *ListEndpointsRequest_Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type ListEndpointsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EndPoints []*v2.NetworkEndPoint `protobuf:"bytes,1,rep,name=end_points,json=endPoints,proto3" json:"end_points,omitempty"`
}

func (x *ListEndpointsResponse) Reset() {
	*x = ListEndpointsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_network_v2_network_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListEndpointsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEndpointsResponse) ProtoMessage() {}

func (x *ListEndpointsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_network_v2_network_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEndpointsResponse.ProtoReflect.Descriptor instead.
func (*ListEndpointsResponse) Descriptor() ([]byte, []int) {
	return file_services_network_v2_network_proto_rawDescGZIP(), []int{1}
}

func (x *ListEndpointsResponse) GetEndPoints() []*v2.NetworkEndPoint {
	if x != nil {
		return x.EndPoints
	}
	return nil
}

type ConfigureRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Ifname      string `protobuf:"bytes,2,opt,name=ifname,proto3" json:"ifname,omitempty"`
	SecondStage bool   `protobuf:"varint,11,opt,name=second_stage,json=secondStage,proto3" json:"second_stage,omitempty"`
}

func (x *ConfigureRequest) Reset() {
	*x = ConfigureRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_network_v2_network_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureRequest) ProtoMessage() {}

func (x *ConfigureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_network_v2_network_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureRequest.ProtoReflect.Descriptor instead.
func (*ConfigureRequest) Descriptor() ([]byte, []int) {
	return file_services_network_v2_network_proto_rawDescGZIP(), []int{2}
}

func (x *ConfigureRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConfigureRequest) GetIfname() string {
	if x != nil {
		return x.Ifname
	}
	return ""
}

func (x *ConfigureRequest) GetSecondStage() bool {
	if x != nil {
		return x.SecondStage
	}
	return false
}

type DeconfigureRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Ifname string `protobuf:"bytes,2,opt,name=ifname,proto3" json:"ifname,omitempty"`
}

func (x *DeconfigureRequest) Reset() {
	*x = DeconfigureRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_network_v2_network_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeconfigureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeconfigureRequest) ProtoMessage() {}

func (x *DeconfigureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_network_v2_network_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeconfigureRequest.ProtoReflect.Descriptor instead.
func (*DeconfigureRequest) Descriptor() ([]byte, []int) {
	return file_services_network_v2_network_proto_rawDescGZIP(), []int{3}
}

func (x *DeconfigureRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeconfigureRequest) GetIfname() string {
	if x != nil {
		return x.Ifname
	}
	return ""
}

type CreateConfRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string                `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Options   *v2.NetworkSchemeOpts `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	Configure bool                  `protobuf:"varint,100,opt,name=configure,proto3" json:"configure,omitempty"`
}

func (x *CreateConfRequest) Reset() {
	*x = CreateConfRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_network_v2_network_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateConfRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateConfRequest) ProtoMessage() {}

func (x *CreateConfRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_network_v2_network_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateConfRequest.ProtoReflect.Descriptor instead.
func (*CreateConfRequest) Descriptor() ([]byte, []int) {
	return file_services_network_v2_network_proto_rawDescGZIP(), []int{4}
}

func (x *CreateConfRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateConfRequest) GetOptions() *v2.NetworkSchemeOpts {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *CreateConfRequest) GetConfigure() bool {
	if x != nil {
		return x.Configure
	}
	return false
}

type UpdateConfRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Ifname string `protobuf:"bytes,2,opt,name=ifname,proto3" json:"ifname,omitempty"`
	// Router specific
	InLimit  *UpdateConfRequest_Limit `protobuf:"bytes,11,opt,name=in_limit,json=inLimit,proto3" json:"in_limit,omitempty"`
	OutLimit *UpdateConfRequest_Limit `protobuf:"bytes,12,opt,name=out_limit,json=outLimit,proto3" json:"out_limit,omitempty"`
	// Common
	Addrs    []*UpdateConfRequest_Addr  `protobuf:"bytes,21,rep,name=addrs,proto3" json:"addrs,omitempty"`
	MTU      *UpdateConfRequest_MTU     `protobuf:"bytes,22,opt,name=mtu,proto3" json:"mtu,omitempty"`
	Gateway4 *UpdateConfRequest_Gateway `protobuf:"bytes,23,opt,name=gateway4,proto3" json:"gateway4,omitempty"`
	Gateway6 *UpdateConfRequest_Gateway `protobuf:"bytes,24,opt,name=gateway6,proto3" json:"gateway6,omitempty"`
	Apply    bool                       `protobuf:"varint,100,opt,name=apply,proto3" json:"apply,omitempty"`
}

func (x *UpdateConfRequest) Reset() {
	*x = UpdateConfRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_network_v2_network_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateConfRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfRequest) ProtoMessage() {}

func (x *UpdateConfRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_network_v2_network_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConfRequest.ProtoReflect.Descriptor instead.
func (*UpdateConfRequest) Descriptor() ([]byte, []int) {
	return file_services_network_v2_network_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateConfRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateConfRequest) GetIfname() string {
	if x != nil {
		return x.Ifname
	}
	return ""
}

func (x *UpdateConfRequest) GetInLimit() *UpdateConfRequest_Limit {
	if x != nil {
		return x.InLimit
	}
	return nil
}

func (x *UpdateConfRequest) GetOutLimit() *UpdateConfRequest_Limit {
	if x != nil {
		return x.OutLimit
	}
	return nil
}

func (x *UpdateConfRequest) GetAddrs() []*UpdateConfRequest_Addr {
	if x != nil {
		return x.Addrs
	}
	return nil
}

func (x *UpdateConfRequest) GetMTU() *UpdateConfRequest_MTU {
	if x != nil {
		return x.MTU
	}
	return nil
}

func (x *UpdateConfRequest) GetGateway4() *UpdateConfRequest_Gateway {
	if x != nil {
		return x.Gateway4
	}
	return nil
}

func (x *UpdateConfRequest) GetGateway6() *UpdateConfRequest_Gateway {
	if x != nil {
		return x.Gateway6
	}
	return nil
}

func (x *UpdateConfRequest) GetApply() bool {
	if x != nil {
		return x.Apply
	}
	return false
}

type DeleteConfRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Ifname      string `protobuf:"bytes,2,opt,name=ifname,proto3" json:"ifname,omitempty"`
	Deconfigure bool   `protobuf:"varint,100,opt,name=deconfigure,proto3" json:"deconfigure,omitempty"`
}

func (x *DeleteConfRequest) Reset() {
	*x = DeleteConfRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_network_v2_network_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteConfRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteConfRequest) ProtoMessage() {}

func (x *DeleteConfRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_network_v2_network_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteConfRequest.ProtoReflect.Descriptor instead.
func (*DeleteConfRequest) Descriptor() ([]byte, []int) {
	return file_services_network_v2_network_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteConfRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeleteConfRequest) GetIfname() string {
	if x != nil {
		return x.Ifname
	}
	return ""
}

func (x *DeleteConfRequest) GetDeconfigure() bool {
	if x != nil {
		return x.Deconfigure
	}
	return false
}

type ListEndpointsRequest_Filter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListEndpointsRequest_Filter) Reset() {
	*x = ListEndpointsRequest_Filter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_network_v2_network_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListEndpointsRequest_Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEndpointsRequest_Filter) ProtoMessage() {}

func (x *ListEndpointsRequest_Filter) ProtoReflect() protoreflect.Message {
	mi := &file_services_network_v2_network_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEndpointsRequest_Filter.ProtoReflect.Descriptor instead.
func (*ListEndpointsRequest_Filter) Descriptor() ([]byte, []int) {
	return file_services_network_v2_network_proto_rawDescGZIP(), []int{0, 0}
}

type UpdateConfRequest_Addr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addr   string                        `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Action UpdateConfRequest_Addr_Action `protobuf:"varint,2,opt,name=action,proto3,enum=kvmrun.api.services.network.v2.UpdateConfRequest_Addr_Action" json:"action,omitempty"`
}

func (x *UpdateConfRequest_Addr) Reset() {
	*x = UpdateConfRequest_Addr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_network_v2_network_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateConfRequest_Addr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfRequest_Addr) ProtoMessage() {}

func (x *UpdateConfRequest_Addr) ProtoReflect() protoreflect.Message {
	mi := &file_services_network_v2_network_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConfRequest_Addr.ProtoReflect.Descriptor instead.
func (*UpdateConfRequest_Addr) Descriptor() ([]byte, []int) {
	return file_services_network_v2_network_proto_rawDescGZIP(), []int{5, 0}
}

func (x *UpdateConfRequest_Addr) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *UpdateConfRequest_Addr) GetAction() UpdateConfRequest_Addr_Action {
	if x != nil {
		return x.Action
	}
	return UpdateConfRequest_Addr_UNKNOWN
}

type UpdateConfRequest_Limit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value uint32 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *UpdateConfRequest_Limit) Reset() {
	*x = UpdateConfRequest_Limit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_network_v2_network_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateConfRequest_Limit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfRequest_Limit) ProtoMessage() {}

func (x *UpdateConfRequest_Limit) ProtoReflect() protoreflect.Message {
	mi := &file_services_network_v2_network_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConfRequest_Limit.ProtoReflect.Descriptor instead.
func (*UpdateConfRequest_Limit) Descriptor() ([]byte, []int) {
	return file_services_network_v2_network_proto_rawDescGZIP(), []int{5, 1}
}

func (x *UpdateConfRequest_Limit) GetValue() uint32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type UpdateConfRequest_MTU struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value uint32 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *UpdateConfRequest_MTU) Reset() {
	*x = UpdateConfRequest_MTU{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_network_v2_network_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateConfRequest_MTU) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfRequest_MTU) ProtoMessage() {}

func (x *UpdateConfRequest_MTU) ProtoReflect() protoreflect.Message {
	mi := &file_services_network_v2_network_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConfRequest_MTU.ProtoReflect.Descriptor instead.
func (*UpdateConfRequest_MTU) Descriptor() ([]byte, []int) {
	return file_services_network_v2_network_proto_rawDescGZIP(), []int{5, 2}
}

func (x *UpdateConfRequest_MTU) GetValue() uint32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type UpdateConfRequest_Gateway struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *UpdateConfRequest_Gateway) Reset() {
	*x = UpdateConfRequest_Gateway{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_network_v2_network_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateConfRequest_Gateway) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfRequest_Gateway) ProtoMessage() {}

func (x *UpdateConfRequest_Gateway) ProtoReflect() protoreflect.Message {
	mi := &file_services_network_v2_network_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConfRequest_Gateway.ProtoReflect.Descriptor instead.
func (*UpdateConfRequest_Gateway) Descriptor() ([]byte, []int) {
	return file_services_network_v2_network_proto_rawDescGZIP(), []int{5, 3}
}

func (x *UpdateConfRequest_Gateway) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_services_network_v2_network_proto protoreflect.FileDescriptor

var file_services_network_v2_network_proto_rawDesc = []byte{
	0x0a, 0x21, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x6e, 0x65, 0x74, 0x77, 0x6f,
	0x72, 0x6b, 0x2f, 0x76, 0x32, 0x2f, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x1e, 0x6b, 0x76, 0x6d, 0x72, 0x75, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b,
	0x2e, 0x76, 0x32, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x16, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x76, 0x32, 0x2f, 0x6e, 0x65, 0x74, 0x77, 0x6f,
	0x72, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x75, 0x0a, 0x14, 0x4c, 0x69, 0x73, 0x74,
	0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x53, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x3b, 0x2e, 0x6b, 0x76, 0x6d, 0x72, 0x75, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x76,
	0x32, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x06, 0x66,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x1a, 0x08, 0x0a, 0x06, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x22,
	0x5c, 0x0a, 0x15, 0x4c, 0x69, 0x73, 0x74, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x43, 0x0a, 0x0a, 0x65, 0x6e, 0x64, 0x5f,
	0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x6b,
	0x76, 0x6d, 0x72, 0x75, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e,
	0x76, 0x32, 0x2e, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x45, 0x6e, 0x64, 0x50, 0x6f, 0x69,
	0x6e, 0x74, 0x52, 0x09, 0x65, 0x6e, 0x64, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x22, 0x61, 0x0a,
	0x10, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x66, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x69, 0x66, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x21, 0x0a,
	0x0c, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x5f, 0x73, 0x74, 0x61, 0x67, 0x65, 0x18, 0x0b, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x0b, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x53, 0x74, 0x61, 0x67, 0x65,
	0x22, 0x40, 0x0a, 0x12, 0x44, 0x65, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x66,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x69, 0x66, 0x6e, 0x61,
	0x6d, 0x65, 0x22, 0x87, 0x01, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e,
	0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x40, 0x0a, 0x07,
	0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e,
	0x6b, 0x76, 0x6d, 0x72, 0x75, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73,
	0x2e, 0x76, 0x32, 0x2e, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x53, 0x63, 0x68, 0x65, 0x6d,
	0x65, 0x4f, 0x70, 0x74, 0x73, 0x52, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1c,
	0x0a, 0x09, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x18, 0x64, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x09, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x22, 0xc4, 0x06, 0x0a,
	0x11, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x66, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x69, 0x66, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x52,
	0x0a, 0x08, 0x69, 0x6e, 0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x37, 0x2e, 0x6b, 0x76, 0x6d, 0x72, 0x75, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x76,
	0x32, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x2e, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x52, 0x07, 0x69, 0x6e, 0x4c, 0x69, 0x6d,
	0x69, 0x74, 0x12, 0x54, 0x0a, 0x09, 0x6f, 0x75, 0x74, 0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18,
	0x0c, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x37, 0x2e, 0x6b, 0x76, 0x6d, 0x72, 0x75, 0x6e, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x6e, 0x65, 0x74, 0x77,
	0x6f, 0x72, 0x6b, 0x2e, 0x76, 0x32, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e,
	0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x52, 0x08,
	0x6f, 0x75, 0x74, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x4c, 0x0a, 0x05, 0x61, 0x64, 0x64, 0x72,
	0x73, 0x18, 0x15, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x36, 0x2e, 0x6b, 0x76, 0x6d, 0x72, 0x75, 0x6e,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x6e, 0x65,
	0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x76, 0x32, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43,
	0x6f, 0x6e, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x52,
	0x05, 0x61, 0x64, 0x64, 0x72, 0x73, 0x12, 0x47, 0x0a, 0x03, 0x6d, 0x74, 0x75, 0x18, 0x16, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x35, 0x2e, 0x6b, 0x76, 0x6d, 0x72, 0x75, 0x6e, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72,
	0x6b, 0x2e, 0x76, 0x32, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x4d, 0x54, 0x55, 0x52, 0x03, 0x6d, 0x74, 0x75, 0x12,
	0x55, 0x0a, 0x08, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x34, 0x18, 0x17, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x39, 0x2e, 0x6b, 0x76, 0x6d, 0x72, 0x75, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e,
	0x76, 0x32, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x2e, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x52, 0x08, 0x67, 0x61,
	0x74, 0x65, 0x77, 0x61, 0x79, 0x34, 0x12, 0x55, 0x0a, 0x08, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61,
	0x79, 0x36, 0x18, 0x18, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x39, 0x2e, 0x6b, 0x76, 0x6d, 0x72, 0x75,
	0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x6e,
	0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x76, 0x32, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x43, 0x6f, 0x6e, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x47, 0x61, 0x74, 0x65,
	0x77, 0x61, 0x79, 0x52, 0x08, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x36, 0x12, 0x14, 0x0a,
	0x05, 0x61, 0x70, 0x70, 0x6c, 0x79, 0x18, 0x64, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x61, 0x70,
	0x70, 0x6c, 0x79, 0x1a, 0xa0, 0x01, 0x0a, 0x04, 0x41, 0x64, 0x64, 0x72, 0x12, 0x12, 0x0a, 0x04,
	0x61, 0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x64, 0x64, 0x72,
	0x12, 0x55, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x3d, 0x2e, 0x6b, 0x76, 0x6d, 0x72, 0x75, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x76,
	0x32, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x2d, 0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0a,
	0x0a, 0x06, 0x41, 0x50, 0x50, 0x45, 0x4e, 0x44, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x52, 0x45,
	0x4d, 0x4f, 0x56, 0x45, 0x10, 0x02, 0x1a, 0x1d, 0x0a, 0x05, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x1a, 0x1b, 0x0a, 0x03, 0x4d, 0x54, 0x55, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x1a, 0x1f, 0x0a, 0x07, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x22, 0x61, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6f, 0x6e,
	0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x69, 0x66, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x69, 0x66,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x75, 0x72, 0x65, 0x18, 0x64, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x64, 0x65, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x32, 0xd7, 0x04, 0x0a, 0x0e, 0x4e, 0x65, 0x74, 0x77, 0x6f,
	0x72, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x7e, 0x0a, 0x0d, 0x4c, 0x69, 0x73,
	0x74, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x12, 0x34, 0x2e, 0x6b, 0x76, 0x6d,
	0x72, 0x75, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73,
	0x2e, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x76, 0x32, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x35, 0x2e, 0x6b, 0x76, 0x6d, 0x72, 0x75, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x76,
	0x32, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x57, 0x0a, 0x09, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x12, 0x30, 0x2e, 0x6b, 0x76, 0x6d, 0x72, 0x75, 0x6e, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x6e, 0x65, 0x74,
	0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x76, 0x32, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x22, 0x00, 0x12, 0x5b, 0x0a, 0x0b, 0x44, 0x65, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72,
	0x65, 0x12, 0x32, 0x2e, 0x6b, 0x76, 0x6d, 0x72, 0x75, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e,
	0x76, 0x32, 0x2e, 0x44, 0x65, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12,
	0x59, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x12, 0x31, 0x2e,
	0x6b, 0x76, 0x6d, 0x72, 0x75, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x73, 0x2e, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x76, 0x32, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x59, 0x0a, 0x0a, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x12, 0x31, 0x2e, 0x6b, 0x76, 0x6d, 0x72, 0x75,
	0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x6e,
	0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x76, 0x32, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x43, 0x6f, 0x6e, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x59, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43,
	0x6f, 0x6e, 0x66, 0x12, 0x31, 0x2e, 0x6b, 0x76, 0x6d, 0x72, 0x75, 0x6e, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72,
	0x6b, 0x2e, 0x76, 0x32, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00,
	0x42, 0x3a, 0x5a, 0x38, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x30,
	0x78, 0x65, 0x66, 0x35, 0x33, 0x2f, 0x6b, 0x76, 0x6d, 0x72, 0x75, 0x6e, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72,
	0x6b, 0x2f, 0x76, 0x32, 0x3b, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_services_network_v2_network_proto_rawDescOnce sync.Once
	file_services_network_v2_network_proto_rawDescData = file_services_network_v2_network_proto_rawDesc
)

func file_services_network_v2_network_proto_rawDescGZIP() []byte {
	file_services_network_v2_network_proto_rawDescOnce.Do(func() {
		file_services_network_v2_network_proto_rawDescData = protoimpl.X.CompressGZIP(file_services_network_v2_network_proto_rawDescData)
	})
	return file_services_network_v2_network_proto_rawDescData
}

var file_services_network_v2_network_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_services_network_v2_network_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_services_network_v2_network_proto_goTypes = []interface{}{
	(UpdateConfRequest_Addr_Action)(0),  // 0: kvmrun.api.services.network.v2.UpdateConfRequest.Addr.Action
	(*ListEndpointsRequest)(nil),        // 1: kvmrun.api.services.network.v2.ListEndpointsRequest
	(*ListEndpointsResponse)(nil),       // 2: kvmrun.api.services.network.v2.ListEndpointsResponse
	(*ConfigureRequest)(nil),            // 3: kvmrun.api.services.network.v2.ConfigureRequest
	(*DeconfigureRequest)(nil),          // 4: kvmrun.api.services.network.v2.DeconfigureRequest
	(*CreateConfRequest)(nil),           // 5: kvmrun.api.services.network.v2.CreateConfRequest
	(*UpdateConfRequest)(nil),           // 6: kvmrun.api.services.network.v2.UpdateConfRequest
	(*DeleteConfRequest)(nil),           // 7: kvmrun.api.services.network.v2.DeleteConfRequest
	(*ListEndpointsRequest_Filter)(nil), // 8: kvmrun.api.services.network.v2.ListEndpointsRequest.Filter
	(*UpdateConfRequest_Addr)(nil),      // 9: kvmrun.api.services.network.v2.UpdateConfRequest.Addr
	(*UpdateConfRequest_Limit)(nil),     // 10: kvmrun.api.services.network.v2.UpdateConfRequest.Limit
	(*UpdateConfRequest_MTU)(nil),       // 11: kvmrun.api.services.network.v2.UpdateConfRequest.MTU
	(*UpdateConfRequest_Gateway)(nil),   // 12: kvmrun.api.services.network.v2.UpdateConfRequest.Gateway
	(*v2.NetworkEndPoint)(nil),          // 13: kvmrun.api.types.v2.NetworkEndPoint
	(*v2.NetworkSchemeOpts)(nil),        // 14: kvmrun.api.types.v2.NetworkSchemeOpts
	(*emptypb.Empty)(nil),               // 15: google.protobuf.Empty
}
var file_services_network_v2_network_proto_depIdxs = []int32{
	8,  // 0: kvmrun.api.services.network.v2.ListEndpointsRequest.filter:type_name -> kvmrun.api.services.network.v2.ListEndpointsRequest.Filter
	13, // 1: kvmrun.api.services.network.v2.ListEndpointsResponse.end_points:type_name -> kvmrun.api.types.v2.NetworkEndPoint
	14, // 2: kvmrun.api.services.network.v2.CreateConfRequest.options:type_name -> kvmrun.api.types.v2.NetworkSchemeOpts
	10, // 3: kvmrun.api.services.network.v2.UpdateConfRequest.in_limit:type_name -> kvmrun.api.services.network.v2.UpdateConfRequest.Limit
	10, // 4: kvmrun.api.services.network.v2.UpdateConfRequest.out_limit:type_name -> kvmrun.api.services.network.v2.UpdateConfRequest.Limit
	9,  // 5: kvmrun.api.services.network.v2.UpdateConfRequest.addrs:type_name -> kvmrun.api.services.network.v2.UpdateConfRequest.Addr
	11, // 6: kvmrun.api.services.network.v2.UpdateConfRequest.mtu:type_name -> kvmrun.api.services.network.v2.UpdateConfRequest.MTU
	12, // 7: kvmrun.api.services.network.v2.UpdateConfRequest.gateway4:type_name -> kvmrun.api.services.network.v2.UpdateConfRequest.Gateway
	12, // 8: kvmrun.api.services.network.v2.UpdateConfRequest.gateway6:type_name -> kvmrun.api.services.network.v2.UpdateConfRequest.Gateway
	0,  // 9: kvmrun.api.services.network.v2.UpdateConfRequest.Addr.action:type_name -> kvmrun.api.services.network.v2.UpdateConfRequest.Addr.Action
	1,  // 10: kvmrun.api.services.network.v2.NetworkService.ListEndpoints:input_type -> kvmrun.api.services.network.v2.ListEndpointsRequest
	3,  // 11: kvmrun.api.services.network.v2.NetworkService.Configure:input_type -> kvmrun.api.services.network.v2.ConfigureRequest
	4,  // 12: kvmrun.api.services.network.v2.NetworkService.Deconfigure:input_type -> kvmrun.api.services.network.v2.DeconfigureRequest
	5,  // 13: kvmrun.api.services.network.v2.NetworkService.CreateConf:input_type -> kvmrun.api.services.network.v2.CreateConfRequest
	6,  // 14: kvmrun.api.services.network.v2.NetworkService.UpdateConf:input_type -> kvmrun.api.services.network.v2.UpdateConfRequest
	7,  // 15: kvmrun.api.services.network.v2.NetworkService.DeleteConf:input_type -> kvmrun.api.services.network.v2.DeleteConfRequest
	2,  // 16: kvmrun.api.services.network.v2.NetworkService.ListEndpoints:output_type -> kvmrun.api.services.network.v2.ListEndpointsResponse
	15, // 17: kvmrun.api.services.network.v2.NetworkService.Configure:output_type -> google.protobuf.Empty
	15, // 18: kvmrun.api.services.network.v2.NetworkService.Deconfigure:output_type -> google.protobuf.Empty
	15, // 19: kvmrun.api.services.network.v2.NetworkService.CreateConf:output_type -> google.protobuf.Empty
	15, // 20: kvmrun.api.services.network.v2.NetworkService.UpdateConf:output_type -> google.protobuf.Empty
	15, // 21: kvmrun.api.services.network.v2.NetworkService.DeleteConf:output_type -> google.protobuf.Empty
	16, // [16:22] is the sub-list for method output_type
	10, // [10:16] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_services_network_v2_network_proto_init() }
func file_services_network_v2_network_proto_init() {
	if File_services_network_v2_network_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_services_network_v2_network_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListEndpointsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_network_v2_network_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListEndpointsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_network_v2_network_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigureRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_network_v2_network_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeconfigureRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_network_v2_network_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateConfRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_network_v2_network_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateConfRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_network_v2_network_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteConfRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_network_v2_network_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListEndpointsRequest_Filter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_network_v2_network_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateConfRequest_Addr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_network_v2_network_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateConfRequest_Limit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_network_v2_network_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateConfRequest_MTU); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_network_v2_network_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateConfRequest_Gateway); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_services_network_v2_network_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_network_v2_network_proto_goTypes,
		DependencyIndexes: file_services_network_v2_network_proto_depIdxs,
		EnumInfos:         file_services_network_v2_network_proto_enumTypes,
		MessageInfos:      file_services_network_v2_network_proto_msgTypes,
	}.Build()
	File_services_network_v2_network_proto = out.File
	file_services_network_v2_network_proto_rawDesc = nil
	file_services_network_v2_network_proto_goTypes = nil
	file_services_network_v2_network_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// NetworkServiceClient is the client API for NetworkService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NetworkServiceClient interface {
	ListEndpoints(ctx context.Context, in *ListEndpointsRequest, opts ...grpc.CallOption) (*ListEndpointsResponse, error)
	Configure(ctx context.Context, in *ConfigureRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Deconfigure(ctx context.Context, in *DeconfigureRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	CreateConf(ctx context.Context, in *CreateConfRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UpdateConf(ctx context.Context, in *UpdateConfRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DeleteConf(ctx context.Context, in *DeleteConfRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type networkServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNetworkServiceClient(cc grpc.ClientConnInterface) NetworkServiceClient {
	return &networkServiceClient{cc}
}

func (c *networkServiceClient) ListEndpoints(ctx context.Context, in *ListEndpointsRequest, opts ...grpc.CallOption) (*ListEndpointsResponse, error) {
	out := new(ListEndpointsResponse)
	err := c.cc.Invoke(ctx, "/kvmrun.api.services.network.v2.NetworkService/ListEndpoints", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkServiceClient) Configure(ctx context.Context, in *ConfigureRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/kvmrun.api.services.network.v2.NetworkService/Configure", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkServiceClient) Deconfigure(ctx context.Context, in *DeconfigureRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/kvmrun.api.services.network.v2.NetworkService/Deconfigure", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkServiceClient) CreateConf(ctx context.Context, in *CreateConfRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/kvmrun.api.services.network.v2.NetworkService/CreateConf", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkServiceClient) UpdateConf(ctx context.Context, in *UpdateConfRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/kvmrun.api.services.network.v2.NetworkService/UpdateConf", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkServiceClient) DeleteConf(ctx context.Context, in *DeleteConfRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/kvmrun.api.services.network.v2.NetworkService/DeleteConf", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NetworkServiceServer is the server API for NetworkService service.
type NetworkServiceServer interface {
	ListEndpoints(context.Context, *ListEndpointsRequest) (*ListEndpointsResponse, error)
	Configure(context.Context, *ConfigureRequest) (*emptypb.Empty, error)
	Deconfigure(context.Context, *DeconfigureRequest) (*emptypb.Empty, error)
	CreateConf(context.Context, *CreateConfRequest) (*emptypb.Empty, error)
	UpdateConf(context.Context, *UpdateConfRequest) (*emptypb.Empty, error)
	DeleteConf(context.Context, *DeleteConfRequest) (*emptypb.Empty, error)
}

// UnimplementedNetworkServiceServer can be embedded to have forward compatible implementations.
type UnimplementedNetworkServiceServer struct {
}

func (*UnimplementedNetworkServiceServer) ListEndpoints(context.Context, *ListEndpointsRequest) (*ListEndpointsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListEndpoints not implemented")
}
func (*UnimplementedNetworkServiceServer) Configure(context.Context, *ConfigureRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Configure not implemented")
}
func (*UnimplementedNetworkServiceServer) Deconfigure(context.Context, *DeconfigureRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Deconfigure not implemented")
}
func (*UnimplementedNetworkServiceServer) CreateConf(context.Context, *CreateConfRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateConf not implemented")
}
func (*UnimplementedNetworkServiceServer) UpdateConf(context.Context, *UpdateConfRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateConf not implemented")
}
func (*UnimplementedNetworkServiceServer) DeleteConf(context.Context, *DeleteConfRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteConf not implemented")
}

func RegisterNetworkServiceServer(s *grpc.Server, srv NetworkServiceServer) {
	s.RegisterService(&_NetworkService_serviceDesc, srv)
}

func _NetworkService_ListEndpoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEndpointsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkServiceServer).ListEndpoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kvmrun.api.services.network.v2.NetworkService/ListEndpoints",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkServiceServer).ListEndpoints(ctx, req.(*ListEndpointsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkService_Configure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkServiceServer).Configure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kvmrun.api.services.network.v2.NetworkService/Configure",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkServiceServer).Configure(ctx, req.(*ConfigureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkService_Deconfigure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeconfigureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkServiceServer).Deconfigure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kvmrun.api.services.network.v2.NetworkService/Deconfigure",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkServiceServer).Deconfigure(ctx, req.(*DeconfigureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkService_CreateConf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateConfRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkServiceServer).CreateConf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kvmrun.api.services.network.v2.NetworkService/CreateConf",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkServiceServer).CreateConf(ctx, req.(*CreateConfRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkService_UpdateConf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateConfRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkServiceServer).UpdateConf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kvmrun.api.services.network.v2.NetworkService/UpdateConf",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkServiceServer).UpdateConf(ctx, req.(*UpdateConfRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkService_DeleteConf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteConfRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkServiceServer).DeleteConf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kvmrun.api.services.network.v2.NetworkService/DeleteConf",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkServiceServer).DeleteConf(ctx, req.(*DeleteConfRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _NetworkService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kvmrun.api.services.network.v2.NetworkService",
	HandlerType: (*NetworkServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListEndpoints",
			Handler:    _NetworkService_ListEndpoints_Handler,
		},
		{
			MethodName: "Configure",
			Handler:    _NetworkService_Configure_Handler,
		},
		{
			MethodName: "Deconfigure",
			Handler:    _NetworkService_Deconfigure_Handler,
		},
		{
			MethodName: "CreateConf",
			Handler:    _NetworkService_CreateConf_Handler,
		},
		{
			MethodName: "UpdateConf",
			Handler:    _NetworkService_UpdateConf_Handler,
		},
		{
			MethodName: "DeleteConf",
			Handler:    _NetworkService_DeleteConf_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/network/v2/network.proto",
}
