// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.18.3
// source: services/network/v2/network.proto

package network

import (
	context "context"
	v2 "github.com/0xef53/kvmrun/api/types/v2"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListEndpointsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filter *ListEndpointsRequest_Filter `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
}

func (x *ListEndpointsRequest) Reset() {
	*x = ListEndpointsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_network_v2_network_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListEndpointsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEndpointsRequest) ProtoMessage() {}

func (x *ListEndpointsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_network_v2_network_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEndpointsRequest.ProtoReflect.Descriptor instead.
func (*ListEndpointsRequest) Descriptor() ([]byte, []int) {
	return file_services_network_v2_network_proto_rawDescGZIP(), []int{0}
}

func (x *ListEndpointsRequest) GetFilter() *ListEndpointsRequest_Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type ListEndpointsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EndPoints []*v2.NetworkEndPoint `protobuf:"bytes,1,rep,name=end_points,json=endPoints,proto3" json:"end_points,omitempty"`
}

func (x *ListEndpointsResponse) Reset() {
	*x = ListEndpointsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_network_v2_network_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListEndpointsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEndpointsResponse) ProtoMessage() {}

func (x *ListEndpointsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_network_v2_network_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEndpointsResponse.ProtoReflect.Descriptor instead.
func (*ListEndpointsResponse) Descriptor() ([]byte, []int) {
	return file_services_network_v2_network_proto_rawDescGZIP(), []int{1}
}

func (x *ListEndpointsResponse) GetEndPoints() []*v2.NetworkEndPoint {
	if x != nil {
		return x.EndPoints
	}
	return nil
}

type ConfigureRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LinkName string `protobuf:"bytes,1,opt,name=link_name,json=linkName,proto3" json:"link_name,omitempty"`
	// Types that are assignable to Attrs:
	//
	//	*ConfigureRequest_Vlan
	//	*ConfigureRequest_Vxlan
	//	*ConfigureRequest_Router
	//	*ConfigureRequest_Bridge
	Attrs       isConfigureRequest_Attrs `protobuf_oneof:"attrs"`
	SecondStage bool                     `protobuf:"varint,100,opt,name=second_stage,json=secondStage,proto3" json:"second_stage,omitempty"`
}

func (x *ConfigureRequest) Reset() {
	*x = ConfigureRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_network_v2_network_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureRequest) ProtoMessage() {}

func (x *ConfigureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_network_v2_network_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureRequest.ProtoReflect.Descriptor instead.
func (*ConfigureRequest) Descriptor() ([]byte, []int) {
	return file_services_network_v2_network_proto_rawDescGZIP(), []int{2}
}

func (x *ConfigureRequest) GetLinkName() string {
	if x != nil {
		return x.LinkName
	}
	return ""
}

func (m *ConfigureRequest) GetAttrs() isConfigureRequest_Attrs {
	if m != nil {
		return m.Attrs
	}
	return nil
}

func (x *ConfigureRequest) GetVlan() *ConfigureRequest_VlanAttrs {
	if x, ok := x.GetAttrs().(*ConfigureRequest_Vlan); ok {
		return x.Vlan
	}
	return nil
}

func (x *ConfigureRequest) GetVxlan() *ConfigureRequest_VxlanAttrs {
	if x, ok := x.GetAttrs().(*ConfigureRequest_Vxlan); ok {
		return x.Vxlan
	}
	return nil
}

func (x *ConfigureRequest) GetRouter() *ConfigureRequest_RouterAttrs {
	if x, ok := x.GetAttrs().(*ConfigureRequest_Router); ok {
		return x.Router
	}
	return nil
}

func (x *ConfigureRequest) GetBridge() *ConfigureRequest_BridgeAttrs {
	if x, ok := x.GetAttrs().(*ConfigureRequest_Bridge); ok {
		return x.Bridge
	}
	return nil
}

func (x *ConfigureRequest) GetSecondStage() bool {
	if x != nil {
		return x.SecondStage
	}
	return false
}

type isConfigureRequest_Attrs interface {
	isConfigureRequest_Attrs()
}

type ConfigureRequest_Vlan struct {
	Vlan *ConfigureRequest_VlanAttrs `protobuf:"bytes,2,opt,name=vlan,proto3,oneof"`
}

type ConfigureRequest_Vxlan struct {
	Vxlan *ConfigureRequest_VxlanAttrs `protobuf:"bytes,3,opt,name=vxlan,proto3,oneof"`
}

type ConfigureRequest_Router struct {
	Router *ConfigureRequest_RouterAttrs `protobuf:"bytes,4,opt,name=router,proto3,oneof"`
}

type ConfigureRequest_Bridge struct {
	Bridge *ConfigureRequest_BridgeAttrs `protobuf:"bytes,5,opt,name=bridge,proto3,oneof"`
}

func (*ConfigureRequest_Vlan) isConfigureRequest_Attrs() {}

func (*ConfigureRequest_Vxlan) isConfigureRequest_Attrs() {}

func (*ConfigureRequest_Router) isConfigureRequest_Attrs() {}

func (*ConfigureRequest_Bridge) isConfigureRequest_Attrs() {}

type DeconfigureRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LinkName string `protobuf:"bytes,1,opt,name=link_name,json=linkName,proto3" json:"link_name,omitempty"`
	// Types that are assignable to Attrs:
	//
	//	*DeconfigureRequest_Vlan
	//	*DeconfigureRequest_Vxlan
	//	*DeconfigureRequest_Router
	//	*DeconfigureRequest_Bridge
	Attrs isDeconfigureRequest_Attrs `protobuf_oneof:"attrs"`
}

func (x *DeconfigureRequest) Reset() {
	*x = DeconfigureRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_network_v2_network_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeconfigureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeconfigureRequest) ProtoMessage() {}

func (x *DeconfigureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_network_v2_network_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeconfigureRequest.ProtoReflect.Descriptor instead.
func (*DeconfigureRequest) Descriptor() ([]byte, []int) {
	return file_services_network_v2_network_proto_rawDescGZIP(), []int{3}
}

func (x *DeconfigureRequest) GetLinkName() string {
	if x != nil {
		return x.LinkName
	}
	return ""
}

func (m *DeconfigureRequest) GetAttrs() isDeconfigureRequest_Attrs {
	if m != nil {
		return m.Attrs
	}
	return nil
}

func (x *DeconfigureRequest) GetVlan() *DeconfigureRequest_VlanAttrs {
	if x, ok := x.GetAttrs().(*DeconfigureRequest_Vlan); ok {
		return x.Vlan
	}
	return nil
}

func (x *DeconfigureRequest) GetVxlan() *DeconfigureRequest_VxlanAttrs {
	if x, ok := x.GetAttrs().(*DeconfigureRequest_Vxlan); ok {
		return x.Vxlan
	}
	return nil
}

func (x *DeconfigureRequest) GetRouter() *DeconfigureRequest_RouterAttrs {
	if x, ok := x.GetAttrs().(*DeconfigureRequest_Router); ok {
		return x.Router
	}
	return nil
}

func (x *DeconfigureRequest) GetBridge() *DeconfigureRequest_BridgeAttrs {
	if x, ok := x.GetAttrs().(*DeconfigureRequest_Bridge); ok {
		return x.Bridge
	}
	return nil
}

type isDeconfigureRequest_Attrs interface {
	isDeconfigureRequest_Attrs()
}

type DeconfigureRequest_Vlan struct {
	Vlan *DeconfigureRequest_VlanAttrs `protobuf:"bytes,2,opt,name=vlan,proto3,oneof"`
}

type DeconfigureRequest_Vxlan struct {
	Vxlan *DeconfigureRequest_VxlanAttrs `protobuf:"bytes,3,opt,name=vxlan,proto3,oneof"`
}

type DeconfigureRequest_Router struct {
	Router *DeconfigureRequest_RouterAttrs `protobuf:"bytes,4,opt,name=router,proto3,oneof"`
}

type DeconfigureRequest_Bridge struct {
	Bridge *DeconfigureRequest_BridgeAttrs `protobuf:"bytes,5,opt,name=bridge,proto3,oneof"`
}

func (*DeconfigureRequest_Vlan) isDeconfigureRequest_Attrs() {}

func (*DeconfigureRequest_Vxlan) isDeconfigureRequest_Attrs() {}

func (*DeconfigureRequest_Router) isDeconfigureRequest_Attrs() {}

func (*DeconfigureRequest_Bridge) isDeconfigureRequest_Attrs() {}

type ListEndpointsRequest_Filter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListEndpointsRequest_Filter) Reset() {
	*x = ListEndpointsRequest_Filter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_network_v2_network_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListEndpointsRequest_Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEndpointsRequest_Filter) ProtoMessage() {}

func (x *ListEndpointsRequest_Filter) ProtoReflect() protoreflect.Message {
	mi := &file_services_network_v2_network_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEndpointsRequest_Filter.ProtoReflect.Descriptor instead.
func (*ListEndpointsRequest_Filter) Descriptor() ([]byte, []int) {
	return file_services_network_v2_network_proto_rawDescGZIP(), []int{0, 0}
}

type ConfigureRequest_VlanAttrs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VlanID          uint32 `protobuf:"varint,1,opt,name=vlan_id,json=vlanId,proto3" json:"vlan_id,omitempty"`
	MTU             uint32 `protobuf:"varint,2,opt,name=mtu,proto3" json:"mtu,omitempty"`
	ParentInterface string `protobuf:"bytes,3,opt,name=parent_interface,json=parentInterface,proto3" json:"parent_interface,omitempty"`
}

func (x *ConfigureRequest_VlanAttrs) Reset() {
	*x = ConfigureRequest_VlanAttrs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_network_v2_network_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigureRequest_VlanAttrs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureRequest_VlanAttrs) ProtoMessage() {}

func (x *ConfigureRequest_VlanAttrs) ProtoReflect() protoreflect.Message {
	mi := &file_services_network_v2_network_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureRequest_VlanAttrs.ProtoReflect.Descriptor instead.
func (*ConfigureRequest_VlanAttrs) Descriptor() ([]byte, []int) {
	return file_services_network_v2_network_proto_rawDescGZIP(), []int{2, 0}
}

func (x *ConfigureRequest_VlanAttrs) GetVlanID() uint32 {
	if x != nil {
		return x.VlanID
	}
	return 0
}

func (x *ConfigureRequest_VlanAttrs) GetMTU() uint32 {
	if x != nil {
		return x.MTU
	}
	return 0
}

func (x *ConfigureRequest_VlanAttrs) GetParentInterface() string {
	if x != nil {
		return x.ParentInterface
	}
	return ""
}

type ConfigureRequest_VxlanAttrs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VNI           uint32 `protobuf:"varint,1,opt,name=vni,proto3" json:"vni,omitempty"`
	MTU           uint32 `protobuf:"varint,2,opt,name=mtu,proto3" json:"mtu,omitempty"`
	BindInterface string `protobuf:"bytes,3,opt,name=bind_interface,json=bindInterface,proto3" json:"bind_interface,omitempty"`
}

func (x *ConfigureRequest_VxlanAttrs) Reset() {
	*x = ConfigureRequest_VxlanAttrs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_network_v2_network_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigureRequest_VxlanAttrs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureRequest_VxlanAttrs) ProtoMessage() {}

func (x *ConfigureRequest_VxlanAttrs) ProtoReflect() protoreflect.Message {
	mi := &file_services_network_v2_network_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureRequest_VxlanAttrs.ProtoReflect.Descriptor instead.
func (*ConfigureRequest_VxlanAttrs) Descriptor() ([]byte, []int) {
	return file_services_network_v2_network_proto_rawDescGZIP(), []int{2, 1}
}

func (x *ConfigureRequest_VxlanAttrs) GetVNI() uint32 {
	if x != nil {
		return x.VNI
	}
	return 0
}

func (x *ConfigureRequest_VxlanAttrs) GetMTU() uint32 {
	if x != nil {
		return x.MTU
	}
	return 0
}

func (x *ConfigureRequest_VxlanAttrs) GetBindInterface() string {
	if x != nil {
		return x.BindInterface
	}
	return ""
}

type ConfigureRequest_RouterAttrs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addrs          []string `protobuf:"bytes,1,rep,name=addrs,proto3" json:"addrs,omitempty"`
	MTU            uint32   `protobuf:"varint,2,opt,name=mtu,proto3" json:"mtu,omitempty"`
	BindInterface  string   `protobuf:"bytes,3,opt,name=bind_interface,json=bindInterface,proto3" json:"bind_interface,omitempty"`
	DefaultGateway string   `protobuf:"bytes,4,opt,name=default_gateway,json=defaultGateway,proto3" json:"default_gateway,omitempty"`
	InLimit        uint32   `protobuf:"varint,5,opt,name=in_limit,json=inLimit,proto3" json:"in_limit,omitempty"`
	OutLimit       uint32   `protobuf:"varint,6,opt,name=out_limit,json=outLimit,proto3" json:"out_limit,omitempty"`
	ProcessID      uint32   `protobuf:"varint,100,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
}

func (x *ConfigureRequest_RouterAttrs) Reset() {
	*x = ConfigureRequest_RouterAttrs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_network_v2_network_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigureRequest_RouterAttrs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureRequest_RouterAttrs) ProtoMessage() {}

func (x *ConfigureRequest_RouterAttrs) ProtoReflect() protoreflect.Message {
	mi := &file_services_network_v2_network_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureRequest_RouterAttrs.ProtoReflect.Descriptor instead.
func (*ConfigureRequest_RouterAttrs) Descriptor() ([]byte, []int) {
	return file_services_network_v2_network_proto_rawDescGZIP(), []int{2, 2}
}

func (x *ConfigureRequest_RouterAttrs) GetAddrs() []string {
	if x != nil {
		return x.Addrs
	}
	return nil
}

func (x *ConfigureRequest_RouterAttrs) GetMTU() uint32 {
	if x != nil {
		return x.MTU
	}
	return 0
}

func (x *ConfigureRequest_RouterAttrs) GetBindInterface() string {
	if x != nil {
		return x.BindInterface
	}
	return ""
}

func (x *ConfigureRequest_RouterAttrs) GetDefaultGateway() string {
	if x != nil {
		return x.DefaultGateway
	}
	return ""
}

func (x *ConfigureRequest_RouterAttrs) GetInLimit() uint32 {
	if x != nil {
		return x.InLimit
	}
	return 0
}

func (x *ConfigureRequest_RouterAttrs) GetOutLimit() uint32 {
	if x != nil {
		return x.OutLimit
	}
	return 0
}

func (x *ConfigureRequest_RouterAttrs) GetProcessID() uint32 {
	if x != nil {
		return x.ProcessID
	}
	return 0
}

type ConfigureRequest_BridgeAttrs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ifname string `protobuf:"bytes,1,opt,name=ifname,proto3" json:"ifname,omitempty"`
	MTU    uint32 `protobuf:"varint,2,opt,name=mtu,proto3" json:"mtu,omitempty"`
}

func (x *ConfigureRequest_BridgeAttrs) Reset() {
	*x = ConfigureRequest_BridgeAttrs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_network_v2_network_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigureRequest_BridgeAttrs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureRequest_BridgeAttrs) ProtoMessage() {}

func (x *ConfigureRequest_BridgeAttrs) ProtoReflect() protoreflect.Message {
	mi := &file_services_network_v2_network_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureRequest_BridgeAttrs.ProtoReflect.Descriptor instead.
func (*ConfigureRequest_BridgeAttrs) Descriptor() ([]byte, []int) {
	return file_services_network_v2_network_proto_rawDescGZIP(), []int{2, 3}
}

func (x *ConfigureRequest_BridgeAttrs) GetIfname() string {
	if x != nil {
		return x.Ifname
	}
	return ""
}

func (x *ConfigureRequest_BridgeAttrs) GetMTU() uint32 {
	if x != nil {
		return x.MTU
	}
	return 0
}

type DeconfigureRequest_VlanAttrs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VlanID uint32 `protobuf:"varint,1,opt,name=vlan_id,json=vlanId,proto3" json:"vlan_id,omitempty"`
}

func (x *DeconfigureRequest_VlanAttrs) Reset() {
	*x = DeconfigureRequest_VlanAttrs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_network_v2_network_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeconfigureRequest_VlanAttrs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeconfigureRequest_VlanAttrs) ProtoMessage() {}

func (x *DeconfigureRequest_VlanAttrs) ProtoReflect() protoreflect.Message {
	mi := &file_services_network_v2_network_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeconfigureRequest_VlanAttrs.ProtoReflect.Descriptor instead.
func (*DeconfigureRequest_VlanAttrs) Descriptor() ([]byte, []int) {
	return file_services_network_v2_network_proto_rawDescGZIP(), []int{3, 0}
}

func (x *DeconfigureRequest_VlanAttrs) GetVlanID() uint32 {
	if x != nil {
		return x.VlanID
	}
	return 0
}

type DeconfigureRequest_VxlanAttrs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VNI uint32 `protobuf:"varint,1,opt,name=vni,proto3" json:"vni,omitempty"`
}

func (x *DeconfigureRequest_VxlanAttrs) Reset() {
	*x = DeconfigureRequest_VxlanAttrs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_network_v2_network_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeconfigureRequest_VxlanAttrs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeconfigureRequest_VxlanAttrs) ProtoMessage() {}

func (x *DeconfigureRequest_VxlanAttrs) ProtoReflect() protoreflect.Message {
	mi := &file_services_network_v2_network_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeconfigureRequest_VxlanAttrs.ProtoReflect.Descriptor instead.
func (*DeconfigureRequest_VxlanAttrs) Descriptor() ([]byte, []int) {
	return file_services_network_v2_network_proto_rawDescGZIP(), []int{3, 1}
}

func (x *DeconfigureRequest_VxlanAttrs) GetVNI() uint32 {
	if x != nil {
		return x.VNI
	}
	return 0
}

type DeconfigureRequest_RouterAttrs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BindInterface string `protobuf:"bytes,1,opt,name=bind_interface,json=bindInterface,proto3" json:"bind_interface,omitempty"`
}

func (x *DeconfigureRequest_RouterAttrs) Reset() {
	*x = DeconfigureRequest_RouterAttrs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_network_v2_network_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeconfigureRequest_RouterAttrs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeconfigureRequest_RouterAttrs) ProtoMessage() {}

func (x *DeconfigureRequest_RouterAttrs) ProtoReflect() protoreflect.Message {
	mi := &file_services_network_v2_network_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeconfigureRequest_RouterAttrs.ProtoReflect.Descriptor instead.
func (*DeconfigureRequest_RouterAttrs) Descriptor() ([]byte, []int) {
	return file_services_network_v2_network_proto_rawDescGZIP(), []int{3, 2}
}

func (x *DeconfigureRequest_RouterAttrs) GetBindInterface() string {
	if x != nil {
		return x.BindInterface
	}
	return ""
}

type DeconfigureRequest_BridgeAttrs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ifname string `protobuf:"bytes,1,opt,name=ifname,proto3" json:"ifname,omitempty"`
}

func (x *DeconfigureRequest_BridgeAttrs) Reset() {
	*x = DeconfigureRequest_BridgeAttrs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_network_v2_network_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeconfigureRequest_BridgeAttrs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeconfigureRequest_BridgeAttrs) ProtoMessage() {}

func (x *DeconfigureRequest_BridgeAttrs) ProtoReflect() protoreflect.Message {
	mi := &file_services_network_v2_network_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeconfigureRequest_BridgeAttrs.ProtoReflect.Descriptor instead.
func (*DeconfigureRequest_BridgeAttrs) Descriptor() ([]byte, []int) {
	return file_services_network_v2_network_proto_rawDescGZIP(), []int{3, 3}
}

func (x *DeconfigureRequest_BridgeAttrs) GetIfname() string {
	if x != nil {
		return x.Ifname
	}
	return ""
}

var File_services_network_v2_network_proto protoreflect.FileDescriptor

var file_services_network_v2_network_proto_rawDesc = []byte{
	0x0a, 0x21, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x6e, 0x65, 0x74, 0x77, 0x6f,
	0x72, 0x6b, 0x2f, 0x76, 0x32, 0x2f, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x1e, 0x6b, 0x76, 0x6d, 0x72, 0x75, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b,
	0x2e, 0x76, 0x32, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x14, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x76, 0x32, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x75, 0x0a, 0x14, 0x4c, 0x69, 0x73, 0x74, 0x45, 0x6e,
	0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x53,
	0x0a, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x3b,
	0x2e, 0x6b, 0x76, 0x6d, 0x72, 0x75, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x73, 0x2e, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x76, 0x32, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x2e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x06, 0x66, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x1a, 0x08, 0x0a, 0x06, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x22, 0x5c, 0x0a,
	0x15, 0x4c, 0x69, 0x73, 0x74, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x43, 0x0a, 0x0a, 0x65, 0x6e, 0x64, 0x5f, 0x70, 0x6f,
	0x69, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x6b, 0x76, 0x6d,
	0x72, 0x75, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x76, 0x32,
	0x2e, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x45, 0x6e, 0x64, 0x50, 0x6f, 0x69, 0x6e, 0x74,
	0x52, 0x09, 0x65, 0x6e, 0x64, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x22, 0x86, 0x07, 0x0a, 0x10,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x69, 0x6e, 0x6b, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x69, 0x6e, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x50, 0x0a,
	0x04, 0x76, 0x6c, 0x61, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x3a, 0x2e, 0x6b, 0x76,
	0x6d, 0x72, 0x75, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x73, 0x2e, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x76, 0x32, 0x2e, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x56, 0x6c,
	0x61, 0x6e, 0x41, 0x74, 0x74, 0x72, 0x73, 0x48, 0x00, 0x52, 0x04, 0x76, 0x6c, 0x61, 0x6e, 0x12,
	0x53, 0x0a, 0x05, 0x76, 0x78, 0x6c, 0x61, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x3b,
	0x2e, 0x6b, 0x76, 0x6d, 0x72, 0x75, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x73, 0x2e, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x76, 0x32, 0x2e,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x2e, 0x56, 0x78, 0x6c, 0x61, 0x6e, 0x41, 0x74, 0x74, 0x72, 0x73, 0x48, 0x00, 0x52, 0x05, 0x76,
	0x78, 0x6c, 0x61, 0x6e, 0x12, 0x56, 0x0a, 0x06, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x3c, 0x2e, 0x6b, 0x76, 0x6d, 0x72, 0x75, 0x6e, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x6e, 0x65, 0x74, 0x77, 0x6f,
	0x72, 0x6b, 0x2e, 0x76, 0x32, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x41, 0x74, 0x74,
	0x72, 0x73, 0x48, 0x00, 0x52, 0x06, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x12, 0x56, 0x0a, 0x06,
	0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x3c, 0x2e, 0x6b,
	0x76, 0x6d, 0x72, 0x75, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x73, 0x2e, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x76, 0x32, 0x2e, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x42,
	0x72, 0x69, 0x64, 0x67, 0x65, 0x41, 0x74, 0x74, 0x72, 0x73, 0x48, 0x00, 0x52, 0x06, 0x62, 0x72,
	0x69, 0x64, 0x67, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x5f, 0x73,
	0x74, 0x61, 0x67, 0x65, 0x18, 0x64, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x73, 0x65, 0x63, 0x6f,
	0x6e, 0x64, 0x53, 0x74, 0x61, 0x67, 0x65, 0x1a, 0x61, 0x0a, 0x09, 0x56, 0x6c, 0x61, 0x6e, 0x41,
	0x74, 0x74, 0x72, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x76, 0x6c, 0x61, 0x6e, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x76, 0x6c, 0x61, 0x6e, 0x49, 0x64, 0x12, 0x10, 0x0a,
	0x03, 0x6d, 0x74, 0x75, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6d, 0x74, 0x75, 0x12,
	0x29, 0x0a, 0x10, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66,
	0x61, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x70, 0x61, 0x72, 0x65, 0x6e,
	0x74, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x1a, 0x57, 0x0a, 0x0a, 0x56, 0x78,
	0x6c, 0x61, 0x6e, 0x41, 0x74, 0x74, 0x72, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x76, 0x6e, 0x69, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x76, 0x6e, 0x69, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x74,
	0x75, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6d, 0x74, 0x75, 0x12, 0x25, 0x0a, 0x0e,
	0x62, 0x69, 0x6e, 0x64, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x62, 0x69, 0x6e, 0x64, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66,
	0x61, 0x63, 0x65, 0x1a, 0xdc, 0x01, 0x0a, 0x0b, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x41, 0x74,
	0x74, 0x72, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x64, 0x64, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x05, 0x61, 0x64, 0x64, 0x72, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x74, 0x75,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6d, 0x74, 0x75, 0x12, 0x25, 0x0a, 0x0e, 0x62,
	0x69, 0x6e, 0x64, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0d, 0x62, 0x69, 0x6e, 0x64, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61,
	0x63, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x5f, 0x67, 0x61,
	0x74, 0x65, 0x77, 0x61, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x64, 0x65, 0x66,
	0x61, 0x75, 0x6c, 0x74, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x12, 0x19, 0x0a, 0x08, 0x69,
	0x6e, 0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x69,
	0x6e, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x6f, 0x75, 0x74, 0x5f, 0x6c, 0x69,
	0x6d, 0x69, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x6f, 0x75, 0x74, 0x4c, 0x69,
	0x6d, 0x69, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x69,
	0x64, 0x18, 0x64, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73,
	0x49, 0x64, 0x1a, 0x37, 0x0a, 0x0b, 0x42, 0x72, 0x69, 0x64, 0x67, 0x65, 0x41, 0x74, 0x74, 0x72,
	0x73, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x66, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x69, 0x66, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x74, 0x75,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6d, 0x74, 0x75, 0x42, 0x07, 0x0a, 0x05, 0x61,
	0x74, 0x74, 0x72, 0x73, 0x22, 0xbc, 0x04, 0x0a, 0x12, 0x44, 0x65, 0x63, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x75, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x6c,
	0x69, 0x6e, 0x6b, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x6c, 0x69, 0x6e, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x52, 0x0a, 0x04, 0x76, 0x6c, 0x61, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x3c, 0x2e, 0x6b, 0x76, 0x6d, 0x72, 0x75, 0x6e, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x6e, 0x65, 0x74,
	0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x76, 0x32, 0x2e, 0x44, 0x65, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x75, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x56, 0x6c, 0x61, 0x6e, 0x41,
	0x74, 0x74, 0x72, 0x73, 0x48, 0x00, 0x52, 0x04, 0x76, 0x6c, 0x61, 0x6e, 0x12, 0x55, 0x0a, 0x05,
	0x76, 0x78, 0x6c, 0x61, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x3d, 0x2e, 0x6b, 0x76,
	0x6d, 0x72, 0x75, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x73, 0x2e, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x76, 0x32, 0x2e, 0x44, 0x65, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e,
	0x56, 0x78, 0x6c, 0x61, 0x6e, 0x41, 0x74, 0x74, 0x72, 0x73, 0x48, 0x00, 0x52, 0x05, 0x76, 0x78,
	0x6c, 0x61, 0x6e, 0x12, 0x58, 0x0a, 0x06, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x3e, 0x2e, 0x6b, 0x76, 0x6d, 0x72, 0x75, 0x6e, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72,
	0x6b, 0x2e, 0x76, 0x32, 0x2e, 0x44, 0x65, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x41, 0x74,
	0x74, 0x72, 0x73, 0x48, 0x00, 0x52, 0x06, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x12, 0x58, 0x0a,
	0x06, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x3e, 0x2e,
	0x6b, 0x76, 0x6d, 0x72, 0x75, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x73, 0x2e, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x76, 0x32, 0x2e, 0x44,
	0x65, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x2e, 0x42, 0x72, 0x69, 0x64, 0x67, 0x65, 0x41, 0x74, 0x74, 0x72, 0x73, 0x48, 0x00, 0x52,
	0x06, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x1a, 0x24, 0x0a, 0x09, 0x56, 0x6c, 0x61, 0x6e, 0x41,
	0x74, 0x74, 0x72, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x76, 0x6c, 0x61, 0x6e, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x76, 0x6c, 0x61, 0x6e, 0x49, 0x64, 0x1a, 0x1e, 0x0a,
	0x0a, 0x56, 0x78, 0x6c, 0x61, 0x6e, 0x41, 0x74, 0x74, 0x72, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x76,
	0x6e, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x76, 0x6e, 0x69, 0x1a, 0x34, 0x0a,
	0x0b, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x41, 0x74, 0x74, 0x72, 0x73, 0x12, 0x25, 0x0a, 0x0e,
	0x62, 0x69, 0x6e, 0x64, 0x5f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x62, 0x69, 0x6e, 0x64, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66,
	0x61, 0x63, 0x65, 0x1a, 0x25, 0x0a, 0x0b, 0x42, 0x72, 0x69, 0x64, 0x67, 0x65, 0x41, 0x74, 0x74,
	0x72, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x66, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x69, 0x66, 0x6e, 0x61, 0x6d, 0x65, 0x42, 0x07, 0x0a, 0x05, 0x61, 0x74,
	0x74, 0x72, 0x73, 0x32, 0xc6, 0x02, 0x0a, 0x0e, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x7e, 0x0a, 0x0d, 0x4c, 0x69, 0x73, 0x74, 0x45, 0x6e,
	0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x12, 0x34, 0x2e, 0x6b, 0x76, 0x6d, 0x72, 0x75, 0x6e,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x6e, 0x65,
	0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x76, 0x32, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x45, 0x6e, 0x64,
	0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x35, 0x2e,
	0x6b, 0x76, 0x6d, 0x72, 0x75, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x73, 0x2e, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x76, 0x32, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x57, 0x0a, 0x09, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x75, 0x72, 0x65, 0x12, 0x30, 0x2e, 0x6b, 0x76, 0x6d, 0x72, 0x75, 0x6e, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72,
	0x6b, 0x2e, 0x76, 0x32, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12,
	0x5b, 0x0a, 0x0b, 0x44, 0x65, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x12, 0x32,
	0x2e, 0x6b, 0x76, 0x6d, 0x72, 0x75, 0x6e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x73, 0x2e, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x76, 0x32, 0x2e,
	0x44, 0x65, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x42, 0x3a, 0x5a, 0x38,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x30, 0x78, 0x65, 0x66, 0x35,
	0x33, 0x2f, 0x6b, 0x76, 0x6d, 0x72, 0x75, 0x6e, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2f, 0x76, 0x32,
	0x3b, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_services_network_v2_network_proto_rawDescOnce sync.Once
	file_services_network_v2_network_proto_rawDescData = file_services_network_v2_network_proto_rawDesc
)

func file_services_network_v2_network_proto_rawDescGZIP() []byte {
	file_services_network_v2_network_proto_rawDescOnce.Do(func() {
		file_services_network_v2_network_proto_rawDescData = protoimpl.X.CompressGZIP(file_services_network_v2_network_proto_rawDescData)
	})
	return file_services_network_v2_network_proto_rawDescData
}

var file_services_network_v2_network_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_services_network_v2_network_proto_goTypes = []interface{}{
	(*ListEndpointsRequest)(nil),           // 0: kvmrun.api.services.network.v2.ListEndpointsRequest
	(*ListEndpointsResponse)(nil),          // 1: kvmrun.api.services.network.v2.ListEndpointsResponse
	(*ConfigureRequest)(nil),               // 2: kvmrun.api.services.network.v2.ConfigureRequest
	(*DeconfigureRequest)(nil),             // 3: kvmrun.api.services.network.v2.DeconfigureRequest
	(*ListEndpointsRequest_Filter)(nil),    // 4: kvmrun.api.services.network.v2.ListEndpointsRequest.Filter
	(*ConfigureRequest_VlanAttrs)(nil),     // 5: kvmrun.api.services.network.v2.ConfigureRequest.VlanAttrs
	(*ConfigureRequest_VxlanAttrs)(nil),    // 6: kvmrun.api.services.network.v2.ConfigureRequest.VxlanAttrs
	(*ConfigureRequest_RouterAttrs)(nil),   // 7: kvmrun.api.services.network.v2.ConfigureRequest.RouterAttrs
	(*ConfigureRequest_BridgeAttrs)(nil),   // 8: kvmrun.api.services.network.v2.ConfigureRequest.BridgeAttrs
	(*DeconfigureRequest_VlanAttrs)(nil),   // 9: kvmrun.api.services.network.v2.DeconfigureRequest.VlanAttrs
	(*DeconfigureRequest_VxlanAttrs)(nil),  // 10: kvmrun.api.services.network.v2.DeconfigureRequest.VxlanAttrs
	(*DeconfigureRequest_RouterAttrs)(nil), // 11: kvmrun.api.services.network.v2.DeconfigureRequest.RouterAttrs
	(*DeconfigureRequest_BridgeAttrs)(nil), // 12: kvmrun.api.services.network.v2.DeconfigureRequest.BridgeAttrs
	(*v2.NetworkEndPoint)(nil),             // 13: kvmrun.api.types.v2.NetworkEndPoint
	(*emptypb.Empty)(nil),                  // 14: google.protobuf.Empty
}
var file_services_network_v2_network_proto_depIdxs = []int32{
	4,  // 0: kvmrun.api.services.network.v2.ListEndpointsRequest.filter:type_name -> kvmrun.api.services.network.v2.ListEndpointsRequest.Filter
	13, // 1: kvmrun.api.services.network.v2.ListEndpointsResponse.end_points:type_name -> kvmrun.api.types.v2.NetworkEndPoint
	5,  // 2: kvmrun.api.services.network.v2.ConfigureRequest.vlan:type_name -> kvmrun.api.services.network.v2.ConfigureRequest.VlanAttrs
	6,  // 3: kvmrun.api.services.network.v2.ConfigureRequest.vxlan:type_name -> kvmrun.api.services.network.v2.ConfigureRequest.VxlanAttrs
	7,  // 4: kvmrun.api.services.network.v2.ConfigureRequest.router:type_name -> kvmrun.api.services.network.v2.ConfigureRequest.RouterAttrs
	8,  // 5: kvmrun.api.services.network.v2.ConfigureRequest.bridge:type_name -> kvmrun.api.services.network.v2.ConfigureRequest.BridgeAttrs
	9,  // 6: kvmrun.api.services.network.v2.DeconfigureRequest.vlan:type_name -> kvmrun.api.services.network.v2.DeconfigureRequest.VlanAttrs
	10, // 7: kvmrun.api.services.network.v2.DeconfigureRequest.vxlan:type_name -> kvmrun.api.services.network.v2.DeconfigureRequest.VxlanAttrs
	11, // 8: kvmrun.api.services.network.v2.DeconfigureRequest.router:type_name -> kvmrun.api.services.network.v2.DeconfigureRequest.RouterAttrs
	12, // 9: kvmrun.api.services.network.v2.DeconfigureRequest.bridge:type_name -> kvmrun.api.services.network.v2.DeconfigureRequest.BridgeAttrs
	0,  // 10: kvmrun.api.services.network.v2.NetworkService.ListEndpoints:input_type -> kvmrun.api.services.network.v2.ListEndpointsRequest
	2,  // 11: kvmrun.api.services.network.v2.NetworkService.Configure:input_type -> kvmrun.api.services.network.v2.ConfigureRequest
	3,  // 12: kvmrun.api.services.network.v2.NetworkService.Deconfigure:input_type -> kvmrun.api.services.network.v2.DeconfigureRequest
	1,  // 13: kvmrun.api.services.network.v2.NetworkService.ListEndpoints:output_type -> kvmrun.api.services.network.v2.ListEndpointsResponse
	14, // 14: kvmrun.api.services.network.v2.NetworkService.Configure:output_type -> google.protobuf.Empty
	14, // 15: kvmrun.api.services.network.v2.NetworkService.Deconfigure:output_type -> google.protobuf.Empty
	13, // [13:16] is the sub-list for method output_type
	10, // [10:13] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_services_network_v2_network_proto_init() }
func file_services_network_v2_network_proto_init() {
	if File_services_network_v2_network_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_services_network_v2_network_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListEndpointsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_network_v2_network_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListEndpointsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_network_v2_network_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigureRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_network_v2_network_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeconfigureRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_network_v2_network_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListEndpointsRequest_Filter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_network_v2_network_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigureRequest_VlanAttrs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_network_v2_network_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigureRequest_VxlanAttrs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_network_v2_network_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigureRequest_RouterAttrs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_network_v2_network_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigureRequest_BridgeAttrs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_network_v2_network_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeconfigureRequest_VlanAttrs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_network_v2_network_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeconfigureRequest_VxlanAttrs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_network_v2_network_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeconfigureRequest_RouterAttrs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_network_v2_network_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeconfigureRequest_BridgeAttrs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_services_network_v2_network_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*ConfigureRequest_Vlan)(nil),
		(*ConfigureRequest_Vxlan)(nil),
		(*ConfigureRequest_Router)(nil),
		(*ConfigureRequest_Bridge)(nil),
	}
	file_services_network_v2_network_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*DeconfigureRequest_Vlan)(nil),
		(*DeconfigureRequest_Vxlan)(nil),
		(*DeconfigureRequest_Router)(nil),
		(*DeconfigureRequest_Bridge)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_services_network_v2_network_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_network_v2_network_proto_goTypes,
		DependencyIndexes: file_services_network_v2_network_proto_depIdxs,
		MessageInfos:      file_services_network_v2_network_proto_msgTypes,
	}.Build()
	File_services_network_v2_network_proto = out.File
	file_services_network_v2_network_proto_rawDesc = nil
	file_services_network_v2_network_proto_goTypes = nil
	file_services_network_v2_network_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// NetworkServiceClient is the client API for NetworkService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NetworkServiceClient interface {
	ListEndpoints(ctx context.Context, in *ListEndpointsRequest, opts ...grpc.CallOption) (*ListEndpointsResponse, error)
	Configure(ctx context.Context, in *ConfigureRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Deconfigure(ctx context.Context, in *DeconfigureRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type networkServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNetworkServiceClient(cc grpc.ClientConnInterface) NetworkServiceClient {
	return &networkServiceClient{cc}
}

func (c *networkServiceClient) ListEndpoints(ctx context.Context, in *ListEndpointsRequest, opts ...grpc.CallOption) (*ListEndpointsResponse, error) {
	out := new(ListEndpointsResponse)
	err := c.cc.Invoke(ctx, "/kvmrun.api.services.network.v2.NetworkService/ListEndpoints", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkServiceClient) Configure(ctx context.Context, in *ConfigureRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/kvmrun.api.services.network.v2.NetworkService/Configure", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkServiceClient) Deconfigure(ctx context.Context, in *DeconfigureRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/kvmrun.api.services.network.v2.NetworkService/Deconfigure", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NetworkServiceServer is the server API for NetworkService service.
type NetworkServiceServer interface {
	ListEndpoints(context.Context, *ListEndpointsRequest) (*ListEndpointsResponse, error)
	Configure(context.Context, *ConfigureRequest) (*emptypb.Empty, error)
	Deconfigure(context.Context, *DeconfigureRequest) (*emptypb.Empty, error)
}

// UnimplementedNetworkServiceServer can be embedded to have forward compatible implementations.
type UnimplementedNetworkServiceServer struct {
}

func (*UnimplementedNetworkServiceServer) ListEndpoints(context.Context, *ListEndpointsRequest) (*ListEndpointsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListEndpoints not implemented")
}
func (*UnimplementedNetworkServiceServer) Configure(context.Context, *ConfigureRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Configure not implemented")
}
func (*UnimplementedNetworkServiceServer) Deconfigure(context.Context, *DeconfigureRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Deconfigure not implemented")
}

func RegisterNetworkServiceServer(s *grpc.Server, srv NetworkServiceServer) {
	s.RegisterService(&_NetworkService_serviceDesc, srv)
}

func _NetworkService_ListEndpoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEndpointsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkServiceServer).ListEndpoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kvmrun.api.services.network.v2.NetworkService/ListEndpoints",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkServiceServer).ListEndpoints(ctx, req.(*ListEndpointsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkService_Configure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkServiceServer).Configure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kvmrun.api.services.network.v2.NetworkService/Configure",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkServiceServer).Configure(ctx, req.(*ConfigureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkService_Deconfigure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeconfigureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkServiceServer).Deconfigure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kvmrun.api.services.network.v2.NetworkService/Deconfigure",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkServiceServer).Deconfigure(ctx, req.(*DeconfigureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _NetworkService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kvmrun.api.services.network.v2.NetworkService",
	HandlerType: (*NetworkServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListEndpoints",
			Handler:    _NetworkService_ListEndpoints_Handler,
		},
		{
			MethodName: "Configure",
			Handler:    _NetworkService_Configure_Handler,
		},
		{
			MethodName: "Deconfigure",
			Handler:    _NetworkService_Deconfigure_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/network/v2/network.proto",
}
